module Haskell2010.STG.LLVM
  ( STGLLVMError (..)
  , lowerSTGProgramToLLVM
  , lowerSTGProgramToLLVMByName
  , renderSTGLLVMError
  )
where

import Control.Monad (forM_)
import Control.Monad.State.Strict (StateT, get, lift, modify', runStateT)
import Data.Char (ord)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as Text
import Haskell2010.Core.Pretty (renderCorePrimOp, renderCoreType)
import Haskell2010.Core.Syntax
import Haskell2010.Names (RName, nameOcc, nameUnique, renderRName)
import Haskell2010.STG.Syntax
import qualified Haskell2010.STG.Validate as STGValidate
import Haskell2010.Syntax (Literal (..))
import Backend.LLVM.IR
import Backend.LLVM.Validate
import Numeric (showHex)
import Runtime.Int (hintToInteger, mkHIntLiteral, renderIntError)

data STGLLVMError
  = STGLLVMInvalidSTG [STGValidate.STGValidationError]
  | STGLLVMUnknownMain Text
  | STGLLVMAmbiguousMain Text [RName]
  | STGLLVMUnsupported Text
  | STGLLVMInvalidLLVM LLVMValidationError
  deriving stock (Show, Eq)

data ValueRef
  = DirectValue LLVMOperand
  | CapturedValue LLVMOperand Int Int
  deriving stock (Show, Eq, Ord)

type ValueEnv = Map.Map RName ValueRef

data PendingClosure = PendingClosure
  { pendingEnvPointer :: LLVMOperand
  , pendingCaptures :: [RName]
  }
  deriving stock (Show, Eq, Ord)

data AllocatedBinding = AllocatedBinding
  { allocatedName :: RName
  , allocatedObject :: LLVMOperand
  , allocatedPending :: Maybe PendingClosure
  }
  deriving stock (Show, Eq, Ord)

data ModuleState = ModuleState
  { nextClosureFunction :: Int
  , generatedFunctions :: [LLVMFunction]
  }
  deriving stock (Show, Eq)

data FunctionState = FunctionState
  { nextRegister :: Int
  , nextBlock :: Int
  , completedBlocks :: [LLVMBlock]
  , currentLabel :: Text
  , currentInstructions :: [LLVMInstruction]
  }
  deriving stock (Show, Eq)

type ModuleM = StateT ModuleState (Either STGLLVMError)
type FunctionM = StateT FunctionState ModuleM

lowerSTGProgramToLLVM :: Text -> STGProgram -> Either STGLLVMError LLVMModule
lowerSTGProgramToLLVM mainOccurrence program =
  case STGValidate.validateProgram program of
    Left errors -> Left (STGLLVMInvalidSTG errors)
    Right () -> do
      mainBinder <- findMain mainOccurrence program
      lowerValidatedSTGProgram mainBinder program

lowerSTGProgramToLLVMByName :: RName -> STGProgram -> Either STGLLVMError LLVMModule
lowerSTGProgramToLLVMByName mainName program =
  case STGValidate.validateProgram program of
    Left errors -> Left (STGLLVMInvalidSTG errors)
    Right () ->
      case [binder | bind <- stgProgramBinds program, binder <- stgBindersOf bind, stgBinderName binder == mainName] of
        [] -> Left (STGLLVMUnknownMain (nameOcc mainName))
        [mainBinder] -> lowerValidatedSTGProgram mainBinder program
        binders -> Left (STGLLVMAmbiguousMain (nameOcc mainName) (map stgBinderName binders))

lowerValidatedSTGProgram :: STGBinder -> STGProgram -> Either STGLLVMError LLVMModule
lowerValidatedSTGProgram mainBinder program = do
  (mainFunction, moduleState) <- runStateT (lowerMainFunction program mainBinder) initialModuleState
  let llvmModule =
        LLVMModule
          { moduleComments =
              [ "generated by HeggLog Haskell 2010 STG LLVM backend v0"
              , "values are boxed; thunks are forced through a lazy enter/apply runtime"
              , "heap objects use process-lifetime allocation; generated programs do not free or collect them"
              ]
          , moduleGlobals = formatGlobals
          , moduleDeclarations = runtimeDeclarations
          , moduleFunctions = runtimeFunctions <> generatedFunctions moduleState <> [mainFunction]
          }
  mapLeft STGLLVMInvalidLLVM (validateLLVMModule llvmModule)
  pure llvmModule

initialModuleState :: ModuleState
initialModuleState =
  ModuleState
    { nextClosureFunction = 0
    , generatedFunctions = []
    }

findMain :: Text -> STGProgram -> Either STGLLVMError STGBinder
findMain occurrence (STGProgram _ binds) =
  case [binder | bind <- binds, binder <- stgBindersOf bind, nameOcc (stgBinderName binder) == occurrence] of
    [] -> Left (STGLLVMUnknownMain occurrence)
    [binder] -> Right binder
    binders -> Left (STGLLVMAmbiguousMain occurrence (map stgBinderName binders))

lowerMainFunction :: STGProgram -> STGBinder -> ModuleM LLVMFunction
lowerMainFunction (STGProgram _ binds) mainBinder =
  runFunction "main" LI32 [] $ do
    env <- emitRecursiveGroup Map.empty (concatMap bindPairs binds)
    mainObject <- resolveName env (stgBinderName mainBinder)
    if stgBinderType mainBinder == ioTy unitTy
      then do
        _ <- emitForce mainObject
        pure ()
      else do
        printedValue <- printableMainValue (stgBinderType mainBinder) mainObject
        fmt <- formatPointer (stgBinderType mainBinder)
        printedReg <- freshRegister "printed"
        emit (ICall (Just printedReg) LI32 (DirectCall "printf") True [(LPtr, fmt), (operandType printedValue, printedValue)])
    pure (OConstInt LI32 0)

printableMainValue :: CoreType -> LLVMOperand -> FunctionM LLVMOperand
printableMainValue ty value
  | ty == intTy = do
      reg <- freshRegister "main_int"
      emit (ICall (Just reg) LI64 (DirectCall expectIntFunctionName) False [(LPtr, value)])
      pure (OLocal LI64 reg)
  | ty == boolTy = do
      boolReg <- freshRegister "main_bool"
      emit (ICall (Just boolReg) LI1 (DirectCall expectBoolFunctionName) False [(LPtr, value)])
      intReg <- freshRegister "main_bool_i32"
      emit (IZext intReg (OLocal LI1 boolReg) LI32)
      pure (OLocal LI32 intReg)
  | ty == charTy = do
      charReg <- freshRegister "main_char"
      emit (ICall (Just charReg) LI32 (DirectCall expectCharFunctionName) False [(LPtr, value)])
      pure (OLocal LI32 charReg)
  | otherwise =
      throwSTGLLVM (STGLLVMUnsupported ("native Haskell 2010 main must be Int, Bool, or Char, got " <> renderCoreType ty))

formatPointer :: CoreType -> FunctionM LLVMOperand
formatPointer ty = do
  reg <- freshRegister "fmt"
  let formatSpec
        | ty == boolTy = ("haskell2010_fmt_i1", boolFormatBytes)
        | ty == charTy = ("haskell2010_fmt_char", charFormatBytes)
        | otherwise = ("haskell2010_fmt_i64", intFormatBytes)
      (globalName, bytes) = formatSpec
      arrayType = LArray (Text.length bytes) LI8
  emit
    ( IGetElementPtr
        reg
        arrayType
        (OGlobal LPtr globalName)
        [(LI64, OConstInt LI64 0), (LI64, OConstInt LI64 0)]
    )
  pure (OLocal LPtr reg)

emitExpr :: ValueEnv -> STGExpr -> FunctionM LLVMOperand
emitExpr env = \case
  STGAtom atom ->
    emitAtomValue env atom
  STGApp callee arguments _ -> do
    calleeObject <- resolveName env callee
    functionObject <- emitExpectFunction calleeObject
    case arguments of
      [argument] -> do
        argumentObject <- emitAtomAddress env argument
        enterFunction functionObject argumentObject
      _ ->
        throwSTGLLVM
          ( STGLLVMUnsupported
              ("native STG enter/apply currently expects unary curried calls to `" <> renderRName callee <> "`")
          )
  STGLet bind body _ -> do
    env' <- emitBind env bind
    emitExpr env' body
  STGCase scrutinee binder alternatives _ -> do
    scrutineeObject <- emitExpr env scrutinee >>= emitForce
    emitCase env binder alternatives scrutineeObject
  STGPrim op arguments _ ->
    emitPrim env op arguments

emitBind :: ValueEnv -> STGBind -> FunctionM ValueEnv
emitBind env = \case
  STGNonRec binder rhs -> do
    allocated <- emitRhsObject env binder rhs
    let env' = Map.insert (stgBinderName binder) (DirectValue (allocatedObject allocated)) env
    fillPending env' allocated
    pure env'
  STGRec pairs ->
    emitRecursiveGroup env pairs

emitRecursiveGroup :: ValueEnv -> [(STGBinder, STGRhs)] -> FunctionM ValueEnv
emitRecursiveGroup env pairs = do
  let recCaptureEnv =
        Map.union
          (Map.fromList [(stgBinderName binder, DirectValue OConstNull) | (binder, _) <- pairs])
          env
  allocated <- traverse (uncurry (emitRhsObject recCaptureEnv)) pairs
  let recEnv =
        foldr
          (\binding -> Map.insert (allocatedName binding) (DirectValue (allocatedObject binding)))
          env
          allocated
  mapM_ (fillPending recEnv) allocated
  pure recEnv

emitRhsObject :: ValueEnv -> STGBinder -> STGRhs -> FunctionM AllocatedBinding
emitRhsObject env binder rhs =
  case rhs of
    STGFunction [argument] body -> do
      let captures = capturedNames env (freeVarsRhs rhs)
      entry <- defineFunctionEntry "fun" (stgBinderName binder) captures argument body
      envPointer <- emitAllocEnvSlots (length captures)
      object <- emitMakeFunction entry envPointer
      pure (AllocatedBinding (stgBinderName binder) object (Just (PendingClosure envPointer captures)))
    STGFunction arguments _ ->
      throwSTGLLVM
        ( STGLLVMUnsupported
            ( "native STG lowering expects unary curried functions after Core-to-STG lowering; `"
                <> renderRName (stgBinderName binder)
                <> "` has arity "
                <> Text.pack (show (length arguments))
            )
        )
    STGThunk updateFlag body -> do
      let captures = capturedNames env (freeVarsRhs rhs)
      entry <- defineThunkEntry "thunk" (stgBinderName binder) captures body
      envPointer <- emitAllocEnvSlots (length captures)
      object <- emitMakeThunk entry envPointer updateFlag
      pure (AllocatedBinding (stgBinderName binder) object (Just (PendingClosure envPointer captures)))
    STGConstructor name fields resultTy ->
      do
        fieldObjects <- traverse (emitAtomAddress env) fields
        object <- emitConstructorObject name resultTy fieldObjects
        pure (AllocatedBinding (stgBinderName binder) object Nothing)

fillPending :: ValueEnv -> AllocatedBinding -> FunctionM ()
fillPending env allocated =
  case allocatedPending allocated of
    Nothing -> pure ()
    Just pending ->
      forM_ (zip [0 :: Int ..] (pendingCaptures pending)) $ \(index, name) -> do
        value <- resolveName env name
        emitStoreEnvSlot (length (pendingCaptures pending)) (pendingEnvPointer pending) index value

defineFunctionEntry :: Text -> RName -> [RName] -> STGBinder -> STGExpr -> FunctionM Text
defineFunctionEntry prefix name captures argument body =
  lift $ do
    functionName <- freshClosureFunctionName prefix name
    function <-
      runFunction
        functionName
        LPtr
        [(LPtr, Register "env"), (LPtr, Register "arg")]
        $ do
          let envOperand = OLocal LPtr (Register "env")
              argumentOperand = OLocal LPtr (Register "arg")
              capturedEnv = captureEnv envOperand captures
              bodyEnv =
                Map.insert (stgBinderName argument) (DirectValue argumentOperand) capturedEnv
          emitExpr bodyEnv body
    addGeneratedFunction function
    pure functionName

defineThunkEntry :: Text -> RName -> [RName] -> STGExpr -> FunctionM Text
defineThunkEntry prefix name captures body =
  lift $ do
    functionName <- freshClosureFunctionName prefix name
    function <-
      runFunction functionName LPtr [(LPtr, Register "env")] $ do
        let envOperand = OLocal LPtr (Register "env")
        emitExpr (captureEnv envOperand captures) body
    addGeneratedFunction function
    pure functionName

captureEnv :: LLVMOperand -> [RName] -> ValueEnv
captureEnv envOperand captures =
  Map.fromList
    [ (name, CapturedValue envOperand index (length captures))
    | (index, name) <- zip [0 ..] captures
    ]

capturedNames :: ValueEnv -> Set.Set RName -> [RName]
capturedNames env names =
  [name | name <- Map.keys env, name `Set.member` names]

emitAtomValue :: ValueEnv -> STGAtom -> FunctionM LLVMOperand
emitAtomValue env atom =
  emitAtomAddress env atom >>= emitForce

emitAtomAddress :: ValueEnv -> STGAtom -> FunctionM LLVMOperand
emitAtomAddress env = \case
  STGVar name _ ->
    resolveName env name
  STGLit literal _ ->
    emitLiteral literal
  STGCon name ty ->
    emitConstructorObject name ty []

emitLiteral :: Literal -> FunctionM LLVMOperand
emitLiteral = \case
  LInt value ->
    case mkHIntLiteral value of
      Right intValue -> emitMakeInt (hintToInteger intValue)
      Left err -> throwSTGLLVM (STGLLVMUnsupported ("native Int literal is out of range: " <> renderIntError err))
  LChar value ->
    emitMakeChar (fromIntegral (ord value))
  LString value ->
    emitMakeStringLiteral value

emitConstructorObject :: RName -> CoreType -> [LLVMOperand] -> FunctionM LLVMOperand
emitConstructorObject name ty fields
  | ty == boolTy && name == trueDataConName = emitMakeBool (OConstInt LI1 1)
  | ty == boolTy && name == falseDataConName = emitMakeBool (OConstInt LI1 0)
  | otherwise =
      emitMakeData name fields

emitPrim :: ValueEnv -> CorePrimOp -> [STGAtom] -> FunctionM LLVMOperand
emitPrim env op arguments =
  case (op, arguments) of
    (PrimAdd, [lhs, rhs]) -> emitIntBinary env "llvm.sadd.with.overflow.i64" lhs rhs >>= emitMakeIntOperand
    (PrimSub, [lhs, rhs]) -> emitIntBinary env "llvm.ssub.with.overflow.i64" lhs rhs >>= emitMakeIntOperand
    (PrimMul, [lhs, rhs]) -> emitIntBinary env "llvm.smul.with.overflow.i64" lhs rhs >>= emitMakeIntOperand
    (PrimDiv, [lhs, rhs]) -> emitCheckedDiv env lhs rhs >>= emitMakeIntOperand
    (PrimLt, [lhs, rhs]) -> do
      lhsValue <- emitExpectAtomInt env lhs
      rhsValue <- emitExpectAtomInt env rhs
      reg <- freshRegister "lt"
      emit (IIcmp reg ICmpSlt LI64 lhsValue rhsValue)
      emitMakeBool (OLocal LI1 reg)
    (PrimEq, [lhs, rhs])
      | stgAtomType lhs == intTy -> do
          lhsValue <- emitExpectAtomInt env lhs
          rhsValue <- emitExpectAtomInt env rhs
          reg <- freshRegister "eq"
          emit (IIcmp reg ICmpEq LI64 lhsValue rhsValue)
          emitMakeBool (OLocal LI1 reg)
      | stgAtomType lhs == boolTy -> do
          lhsValue <- emitExpectAtomBool env lhs
          rhsValue <- emitExpectAtomBool env rhs
          reg <- freshRegister "eq"
          emit (IIcmp reg ICmpEq LI1 lhsValue rhsValue)
          emitMakeBool (OLocal LI1 reg)
      | stgAtomType lhs == charTy -> do
          lhsValue <- emitExpectAtomChar env lhs
          rhsValue <- emitExpectAtomChar env rhs
          reg <- freshRegister "eq"
          emit (IIcmp reg ICmpEq LI32 lhsValue rhsValue)
          emitMakeBool (OLocal LI1 reg)
      | otherwise ->
          throwSTGLLVM
            ( STGLLVMUnsupported
                ("native equality is implemented for Int, Bool, and Char, got " <> renderCoreType (stgAtomType lhs))
            )
    (PrimNegate, [value]) -> do
      valueOperand <- emitExpectAtomInt env value
      emitCheckedSub (OConstInt LI64 0) valueOperand >>= emitMakeIntOperand
    (PrimCharToInt, [value]) -> do
      valueOperand <- emitExpectAtomChar env value
      extendedReg <- freshRegister "char_i64"
      emit (IZext extendedReg valueOperand LI64)
      emitMakeIntOperand (OLocal LI64 extendedReg)
    (PrimIntToChar, [value]) -> do
      valueOperand <- emitExpectAtomInt env value
      emitCheckCharCode valueOperand
      emitMakeCharOperand valueOperand
    (PrimShowInt, [value]) -> do
      valueOperand <- emitExpectAtomInt env value
      resultReg <- freshRegister "show_int"
      emit (ICall (Just resultReg) LPtr (DirectCall showIntFunctionName) False [(LI64, valueOperand)])
      pure (OLocal LPtr resultReg)
    (PrimShowBool, [value]) -> do
      valueOperand <- emitExpectAtomBool env value
      emitShowBool valueOperand
    (PrimPutStrLn, [value]) -> do
      valueObject <- emitAtomAddress env value
      emit (ICall Nothing LVoid (DirectCall putStrLnFunctionName) False [(LPtr, valueObject)])
      emitConstructorObject unitDataConName unitTy []
    (PrimIOThen, [firstAction, secondAction]) -> do
      firstObject <- emitAtomAddress env firstAction
      _ <- emitForce firstObject
      secondObject <- emitAtomAddress env secondAction
      emitForce secondObject
    (PrimIOBind, [firstAction, continuation]) -> do
      firstObject <- emitAtomAddress env firstAction
      firstResult <- emitForce firstObject
      continuationObject <- emitAtomAddress env continuation
      functionObject <- emitExpectFunction continuationObject
      secondAction <- enterFunction functionObject firstResult
      emitForce secondAction
    (PrimIOReturn, [value]) ->
      emitAtomAddress env value
    _ ->
      throwSTGLLVM
        ( STGLLVMUnsupported
            ( "native primitive lowering received unsupported arity for "
                <> renderCorePrimOp op
                <> ": "
                <> Text.pack (show (length arguments))
            )
        )

emitIntBinary :: ValueEnv -> Text -> STGAtom -> STGAtom -> FunctionM LLVMOperand
emitIntBinary env intrinsic lhs rhs = do
  lhsValue <- emitExpectAtomInt env lhs
  rhsValue <- emitExpectAtomInt env rhs
  emitCheckedIntPrim intrinsic lhsValue rhsValue

emitExpectAtomInt :: ValueEnv -> STGAtom -> FunctionM LLVMOperand
emitExpectAtomInt env atom = do
  object <- emitAtomAddress env atom
  reg <- freshRegister "int"
  emit (ICall (Just reg) LI64 (DirectCall expectIntFunctionName) False [(LPtr, object)])
  pure (OLocal LI64 reg)

emitExpectAtomBool :: ValueEnv -> STGAtom -> FunctionM LLVMOperand
emitExpectAtomBool env atom = do
  object <- emitAtomAddress env atom
  reg <- freshRegister "bool"
  emit (ICall (Just reg) LI1 (DirectCall expectBoolFunctionName) False [(LPtr, object)])
  pure (OLocal LI1 reg)

emitExpectAtomChar :: ValueEnv -> STGAtom -> FunctionM LLVMOperand
emitExpectAtomChar env atom = do
  object <- emitAtomAddress env atom
  reg <- freshRegister "char"
  emit (ICall (Just reg) LI32 (DirectCall expectCharFunctionName) False [(LPtr, object)])
  pure (OLocal LI32 reg)

emitShowBool :: LLVMOperand -> FunctionM LLVMOperand
emitShowBool value = do
  trueLabel <- freshBlockLabel "show_bool_true"
  falseLabel <- freshBlockLabel "show_bool_false"
  resultLabel <- freshBlockLabel "show_bool_join"
  terminateCurrent (TCondBr value trueLabel falseLabel)

  startBlock trueLabel
  trueObject <- emitMakeStringLiteral "True"
  truePredecessor <- getsCurrentLabel
  terminateCurrent (TBr resultLabel)

  startBlock falseLabel
  falseObject <- emitMakeStringLiteral "False"
  falsePredecessor <- getsCurrentLabel
  terminateCurrent (TBr resultLabel)

  startBlock resultLabel
  resultReg <- freshRegister "show_bool"
  emit (IPhi resultReg LPtr [(trueObject, truePredecessor), (falseObject, falsePredecessor)])
  pure (OLocal LPtr resultReg)

emitCheckedIntPrim :: Text -> LLVMOperand -> LLVMOperand -> FunctionM LLVMOperand
emitCheckedIntPrim intrinsic lhs rhs = do
  pairReg <- freshRegister "checked"
  let pairType = LStruct [LI64, LI1]
  emit (ICall (Just pairReg) pairType (DirectCall intrinsic) False [(LI64, lhs), (LI64, rhs)])
  let pairOperand = OLocal pairType pairReg
  valueReg <- freshRegister "value"
  overflowReg <- freshRegister "overflow"
  emit (IExtractValue valueReg LI64 pairOperand 0)
  emit (IExtractValue overflowReg LI1 pairOperand 1)
  abortLabel <- freshBlockLabel "int_overflow"
  continueLabel <- freshBlockLabel "int_ok"
  terminateCurrent (TCondBr (OLocal LI1 overflowReg) abortLabel continueLabel)

  startBlock abortLabel
  emitAbort

  startBlock continueLabel
  pure (OLocal LI64 valueReg)

emitCheckedSub :: LLVMOperand -> LLVMOperand -> FunctionM LLVMOperand
emitCheckedSub =
  emitCheckedIntPrim "llvm.ssub.with.overflow.i64"

emitCheckCharCode :: LLVMOperand -> FunctionM ()
emitCheckCharCode value = do
  belowZeroReg <- freshRegister "char_below_zero"
  emit (IIcmp belowZeroReg ICmpSlt LI64 value (OConstInt LI64 0))
  belowZeroAbortLabel <- freshBlockLabel "char_below_zero_abort"
  upperCheckLabel <- freshBlockLabel "char_upper_check"
  terminateCurrent (TCondBr (OLocal LI1 belowZeroReg) belowZeroAbortLabel upperCheckLabel)

  startBlock belowZeroAbortLabel
  emitAbort

  startBlock upperCheckLabel
  aboveUnicodeReg <- freshRegister "char_above_unicode"
  emit (IIcmp aboveUnicodeReg ICmpSlt LI64 (OConstInt LI64 0x10FFFF) value)
  aboveUnicodeAbortLabel <- freshBlockLabel "char_above_unicode_abort"
  okLabel <- freshBlockLabel "char_ok"
  terminateCurrent (TCondBr (OLocal LI1 aboveUnicodeReg) aboveUnicodeAbortLabel okLabel)

  startBlock aboveUnicodeAbortLabel
  emitAbort

  startBlock okLabel

emitCheckedDiv :: ValueEnv -> STGAtom -> STGAtom -> FunctionM LLVMOperand
emitCheckedDiv env lhs rhs = do
  lhsValue <- emitExpectAtomInt env lhs
  rhsValue <- emitExpectAtomInt env rhs
  zeroReg <- freshRegister "div_zero"
  emit (IIcmp zeroReg ICmpEq LI64 rhsValue (OConstInt LI64 0))
  zeroLabel <- freshBlockLabel "div_zero_abort"
  nonZeroLabel <- freshBlockLabel "div_nonzero"
  terminateCurrent (TCondBr (OLocal LI1 zeroReg) zeroLabel nonZeroLabel)

  startBlock zeroLabel
  emitAbort

  startBlock nonZeroLabel
  minReg <- freshRegister "div_min_lhs"
  emit (IIcmp minReg ICmpEq LI64 lhsValue (OConstInt LI64 minInt64Value))
  overflowCheckLabel <- freshBlockLabel "div_overflow_check"
  okLabel <- freshBlockLabel "div_ok"
  terminateCurrent (TCondBr (OLocal LI1 minReg) overflowCheckLabel okLabel)

  startBlock overflowCheckLabel
  negOneReg <- freshRegister "div_neg_one"
  emit (IIcmp negOneReg ICmpEq LI64 rhsValue (OConstInt LI64 (-1)))
  overflowLabel <- freshBlockLabel "div_overflow_abort"
  terminateCurrent (TCondBr (OLocal LI1 negOneReg) overflowLabel okLabel)

  startBlock overflowLabel
  emitAbort

  startBlock okLabel
  valueReg <- freshRegister "div"
  emit (IDiv valueReg LI64 lhsValue rhsValue)
  pure (OLocal LI64 valueReg)

emitCase :: ValueEnv -> STGBinder -> [STGAlt] -> LLVMOperand -> FunctionM LLVMOperand
emitCase env binder alternatives scrutineeObject = do
  tagValue <- loadObjectI64Field scrutineeObject 1 "case_payload"
  resultLabel <- freshBlockLabel "case_join"
  let caseEnv = Map.insert (stgBinderName binder) (DirectValue scrutineeObject) env
  incoming <- emitCaseDecision caseEnv scrutineeObject tagValue alternatives resultLabel []
  startBlock resultLabel
  case incoming of
    [] ->
      pure OConstNull
    _ -> do
      resultReg <- freshRegister "case_result"
      emit (IPhi resultReg LPtr incoming)
      pure (OLocal LPtr resultReg)

emitCaseDecision ::
  ValueEnv ->
  LLVMOperand ->
  LLVMOperand ->
  [STGAlt] ->
  Text ->
  [(LLVMOperand, Text)] ->
  FunctionM [(LLVMOperand, Text)]
emitCaseDecision env scrutineeObject tagValue alternatives resultLabel incoming =
  case alternatives of
    [] -> do
      emitAbort
      pure incoming
    STGAlt altCon binders body : rest -> do
      case altCon of
        DefaultAlt ->
          emitCaseBody env body resultLabel incoming
        LiteralAlt literal -> do
          matchedLabel <- freshBlockLabel "case_lit"
          nextLabel <- freshBlockLabel "case_next"
          condition <- literalMatchCondition tagValue literal
          terminateCurrent (TCondBr condition matchedLabel nextLabel)
          startBlock matchedLabel
          incoming' <- emitCaseBody env body resultLabel incoming
          startBlock nextLabel
          emitCaseDecision env scrutineeObject tagValue rest resultLabel incoming'
        ConstructorAlt name
          | name == trueDataConName || name == falseDataConName -> do
              matchedLabel <- freshBlockLabel "case_bool"
              nextLabel <- freshBlockLabel "case_next"
              let expected = if name == trueDataConName then 1 else 0
              reg <- freshRegister "case_bool_match"
              emit (IIcmp reg ICmpEq LI64 tagValue (OConstInt LI64 expected))
              terminateCurrent (TCondBr (OLocal LI1 reg) matchedLabel nextLabel)
              startBlock matchedLabel
              incoming' <- emitCaseBody env body resultLabel incoming
              startBlock nextLabel
              emitCaseDecision env scrutineeObject tagValue rest resultLabel incoming'
          | otherwise ->
              emitConstructorCaseBranch env scrutineeObject tagValue name binders body rest resultLabel incoming

emitConstructorCaseBranch ::
  ValueEnv ->
  LLVMOperand ->
  LLVMOperand ->
  RName ->
  [STGBinder] ->
  STGExpr ->
  [STGAlt] ->
  Text ->
  [(LLVMOperand, Text)] ->
  FunctionM [(LLVMOperand, Text)]
emitConstructorCaseBranch env scrutineeObject tagValue name binders body rest resultLabel incoming = do
  matchedLabel <- freshBlockLabel "case_data"
  nextLabel <- freshBlockLabel "case_next"
  reg <- freshRegister "case_data_match"
  emit (IIcmp reg ICmpEq LI64 tagValue (OConstInt LI64 (constructorRuntimeTag name)))
  terminateCurrent (TCondBr (OLocal LI1 reg) matchedLabel nextLabel)
  startBlock matchedLabel
  fieldEnv <- emitConstructorFieldEnv scrutineeObject env binders
  incoming' <- emitCaseBody fieldEnv body resultLabel incoming
  startBlock nextLabel
  emitCaseDecision env scrutineeObject tagValue rest resultLabel incoming'

emitConstructorFieldEnv :: LLVMOperand -> ValueEnv -> [STGBinder] -> FunctionM ValueEnv
emitConstructorFieldEnv scrutineeObject env binders = do
  fieldsPointer <- loadObjectPtrField scrutineeObject 2 "data_fields"
  arity <- loadObjectI64Field scrutineeObject 5 "data_arity"
  arityOk <- freshRegister "data_arity_ok"
  emit (IIcmp arityOk ICmpEq LI64 arity (OConstInt LI64 (fromIntegral (length binders))))
  abortLabel <- freshBlockLabel "data_arity_abort"
  continueLabel <- freshBlockLabel "data_arity_ok"
  terminateCurrent (TCondBr (OLocal LI1 arityOk) continueLabel abortLabel)

  startBlock abortLabel
  emitAbort

  startBlock continueLabel
  fieldBindings <- traverse (loadField fieldsPointer) (zip [0 :: Int ..] binders)
  pure (Map.union (Map.fromList fieldBindings) env)
 where
  loadField fieldsPointer (index, binder) = do
    field <- envSlotPointer (length binders) fieldsPointer index
    reg <- freshRegister "data_field"
    emit (ILoad reg LPtr field)
    pure (stgBinderName binder, DirectValue (OLocal LPtr reg))

emitCaseBody :: ValueEnv -> STGExpr -> Text -> [(LLVMOperand, Text)] -> FunctionM [(LLVMOperand, Text)]
emitCaseBody env body resultLabel incoming = do
  value <- emitExpr env body
  predecessor <- getsCurrentLabel
  terminateCurrent (TBr resultLabel)
  pure (incoming <> [(value, predecessor)])

literalMatchCondition :: LLVMOperand -> Literal -> FunctionM LLVMOperand
literalMatchCondition tagValue = \case
  LInt value ->
    case mkHIntLiteral value of
      Right intValue -> do
        reg <- freshRegister "case_int_match"
        emit (IIcmp reg ICmpEq LI64 tagValue (OConstInt LI64 (hintToInteger intValue)))
        pure (OLocal LI1 reg)
      Left err ->
        throwSTGLLVM (STGLLVMUnsupported ("native Int case literal is out of range: " <> renderIntError err))
  LChar expected -> do
    reg <- freshRegister "case_char_match"
    emit (IIcmp reg ICmpEq LI64 tagValue (OConstInt LI64 (fromIntegral (ord expected))))
    pure (OLocal LI1 reg)
  LString {} ->
    throwSTGLLVM (STGLLVMUnsupported "native String case alternatives are not implemented for Core-0")

resolveName :: ValueEnv -> RName -> FunctionM LLVMOperand
resolveName env name =
  case Map.lookup name env of
    Nothing ->
      throwSTGLLVM (STGLLVMUnsupported ("native STG lowering found unbound variable `" <> renderRName name <> "`"))
    Just (DirectValue operand) ->
      pure operand
    Just (CapturedValue envPointer index count) ->
      emitLoadEnvSlot count envPointer index

emitForce :: LLVMOperand -> FunctionM LLVMOperand
emitForce object = do
  reg <- freshRegister "force"
  emit (ICall (Just reg) LPtr (DirectCall forceFunctionName) False [(LPtr, object)])
  pure (OLocal LPtr reg)

emitExpectFunction :: LLVMOperand -> FunctionM LLVMOperand
emitExpectFunction object = do
  reg <- freshRegister "fun"
  emit (ICall (Just reg) LPtr (DirectCall expectFunctionName) False [(LPtr, object)])
  pure (OLocal LPtr reg)

enterFunction :: LLVMOperand -> LLVMOperand -> FunctionM LLVMOperand
enterFunction functionObject argumentObject = do
  code <- loadObjectPtrField functionObject 2 "fun_code"
  closureEnv <- loadObjectPtrField functionObject 3 "fun_env"
  resultReg <- freshRegister "call"
  emit
    ( ICall
        (Just resultReg)
        LPtr
        (IndirectCall code)
        False
        [(LPtr, closureEnv), (LPtr, argumentObject)]
    )
  pure (OLocal LPtr resultReg)

emitMakeInt :: Integer -> FunctionM LLVMOperand
emitMakeInt value =
  emitMakeIntOperand (OConstInt LI64 value)

emitMakeIntOperand :: LLVMOperand -> FunctionM LLVMOperand
emitMakeIntOperand value = do
  reg <- freshRegister "boxed_int"
  emit (ICall (Just reg) LPtr (DirectCall makeIntFunctionName) False [(LI64, value)])
  pure (OLocal LPtr reg)

emitMakeBool :: LLVMOperand -> FunctionM LLVMOperand
emitMakeBool value = do
  reg <- freshRegister "boxed_bool"
  emit (ICall (Just reg) LPtr (DirectCall makeBoolFunctionName) False [(LI1, value)])
  pure (OLocal LPtr reg)

emitMakeChar :: Integer -> FunctionM LLVMOperand
emitMakeChar value =
  emitMakeCharOperand (OConstInt LI64 value)

emitMakeCharOperand :: LLVMOperand -> FunctionM LLVMOperand
emitMakeCharOperand value = do
  reg <- freshRegister "boxed_char"
  emit (ICall (Just reg) LPtr (DirectCall makeCharFunctionName) False [(LI64, value)])
  pure (OLocal LPtr reg)

emitMakeStringLiteral :: Text -> FunctionM LLVMOperand
emitMakeStringLiteral value =
  Text.foldr cons nil value
 where
  nil =
    emitConstructorObject listNilDataConName stringTy []
  cons char tailAction = do
    headObject <- emitMakeChar (fromIntegral (ord char))
    tailObject <- tailAction
    emitConstructorObject listConsDataConName stringTy [headObject, tailObject]

emitMakeData :: RName -> [LLVMOperand] -> FunctionM LLVMOperand
emitMakeData name fields = do
  fieldsPointer <- emitAllocEnvSlots (length fields)
  forM_ (zip [0 :: Int ..] fields) $ \(index, fieldObject) ->
    emitStoreEnvSlot (length fields) fieldsPointer index fieldObject
  reg <- freshRegister "boxed_data"
  emit
    ( ICall
        (Just reg)
        LPtr
        (DirectCall makeDataFunctionName)
        False
        [ (LI64, OConstInt LI64 (constructorRuntimeTag name))
        , (LI64, OConstInt LI64 (fromIntegral (length fields)))
        , (LPtr, fieldsPointer)
        ]
    )
  pure (OLocal LPtr reg)

emitMakeFunction :: Text -> LLVMOperand -> FunctionM LLVMOperand
emitMakeFunction entry envPointer = do
  reg <- freshRegister "function"
  emit
    ( ICall
        (Just reg)
        LPtr
        (DirectCall makeFunctionFunctionName)
        False
        [(LPtr, OGlobal LPtr entry), (LPtr, envPointer)]
    )
  pure (OLocal LPtr reg)

emitMakeThunk :: Text -> LLVMOperand -> STGUpdateFlag -> FunctionM LLVMOperand
emitMakeThunk entry envPointer updateFlag = do
  reg <- freshRegister "thunk"
  emit
    ( ICall
        (Just reg)
        LPtr
        (DirectCall makeThunkFunctionName)
        False
        [(LPtr, OGlobal LPtr entry), (LPtr, envPointer), (LI64, OConstInt LI64 (updateFlagCode updateFlag))]
    )
  pure (OLocal LPtr reg)

emitAllocEnvSlots :: Int -> FunctionM LLVMOperand
emitAllocEnvSlots count
  | count == 0 = pure OConstNull
  | otherwise = do
      envReg <- freshRegister "env"
      emit
        ( ICall
            (Just envReg)
            LPtr
            (DirectCall processLifetimeAllocFunctionName)
            False
            [(LI64, OConstInt LI64 (fromIntegral (8 * count)))]
        )
      pure (OLocal LPtr envReg)

emitStoreEnvSlot :: Int -> LLVMOperand -> Int -> LLVMOperand -> FunctionM ()
emitStoreEnvSlot count envPointer index value = do
  slot <- envSlotPointer count envPointer index
  emit (IStore LPtr value slot)

emitLoadEnvSlot :: Int -> LLVMOperand -> Int -> FunctionM LLVMOperand
emitLoadEnvSlot count envPointer index = do
  slot <- envSlotPointer count envPointer index
  reg <- freshRegister "capture"
  emit (ILoad reg LPtr slot)
  pure (OLocal LPtr reg)

envSlotPointer :: Int -> LLVMOperand -> Int -> FunctionM LLVMOperand
envSlotPointer count envPointer index = do
  reg <- freshRegister "env_slot"
  emit
    ( IGetElementPtr
        reg
        (LArray count LPtr)
        envPointer
        [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 (fromIntegral index))]
    )
  pure (OLocal LPtr reg)

loadObjectI64Field :: LLVMOperand -> Int -> Text -> FunctionM LLVMOperand
loadObjectI64Field object index prefix = do
  field <- objectFieldPointer object index
  reg <- freshRegister prefix
  emit (ILoad reg LI64 field)
  pure (OLocal LI64 reg)

loadObjectPtrField :: LLVMOperand -> Int -> Text -> FunctionM LLVMOperand
loadObjectPtrField object index prefix = do
  field <- objectFieldPointer object index
  reg <- freshRegister prefix
  emit (ILoad reg LPtr field)
  pure (OLocal LPtr reg)

objectFieldPointer :: LLVMOperand -> Int -> FunctionM LLVMOperand
objectFieldPointer object index = do
  reg <- freshRegister "obj_field"
  emit
    ( IGetElementPtr
        reg
        objectType
        object
        [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 (fromIntegral index))]
    )
  pure (OLocal LPtr reg)

emitAbort :: FunctionM ()
emitAbort = do
  emit (ICall Nothing LVoid (DirectCall "abort") False [])
  terminateCurrent TUnreachable

runFunction :: Text -> LLVMType -> [(LLVMType, Register)] -> FunctionM LLVMOperand -> ModuleM LLVMFunction
runFunction name returnType params action = do
  (_, finalState) <-
    runStateT
      ( do
          value <- action
          terminateCurrent (TRet returnType value)
      )
      initialFunctionState
  pure
    LLVMFunction
      { functionName = name
      , functionReturnType = returnType
      , functionParams = params
      , functionBlocks = completedBlocks finalState
      }

initialFunctionState :: FunctionState
initialFunctionState =
  FunctionState
    { nextRegister = 0
    , nextBlock = 0
    , completedBlocks = []
    , currentLabel = "entry"
    , currentInstructions = []
    }

freshRegister :: Text -> FunctionM Register
freshRegister prefix = do
  state <- get
  let reg = Register (prefix <> Text.pack (show (nextRegister state)))
  modify' (\st -> st {nextRegister = nextRegister st + 1})
  pure reg

freshBlockLabel :: Text -> FunctionM Text
freshBlockLabel prefix = do
  state <- get
  let label = "bb_" <> prefix <> Text.pack (show (nextBlock state))
  modify' (\st -> st {nextBlock = nextBlock st + 1})
  pure label

getsCurrentLabel :: FunctionM Text
getsCurrentLabel =
  currentLabel <$> get

terminateCurrent :: LLVMTerminator -> FunctionM ()
terminateCurrent terminator = do
  state <- get
  let block =
        LLVMBlock
          { blockLabel = currentLabel state
          , blockInstructions = currentInstructions state
          , blockTerminator = terminator
          }
  modify' $
    \st ->
      st
        { completedBlocks = completedBlocks st <> [block]
        , currentInstructions = []
        }

startBlock :: Text -> FunctionM ()
startBlock label =
  modify' (\state -> state {currentLabel = label, currentInstructions = []})

emit :: LLVMInstruction -> FunctionM ()
emit instruction =
  modify' (\state -> state {currentInstructions = currentInstructions state <> [instruction]})

freshClosureFunctionName :: Text -> RName -> ModuleM Text
freshClosureFunctionName prefix name = do
  state <- get
  let index = nextClosureFunction state
      functionName =
        "hegglog_hs_"
          <> prefix
          <> "_"
          <> sanitizeName (nameOcc name)
          <> "_u"
          <> Text.pack (show (nameUnique name))
          <> "_"
          <> Text.pack (show index)
  modify' (\st -> st {nextClosureFunction = index + 1})
  pure functionName

addGeneratedFunction :: LLVMFunction -> ModuleM ()
addGeneratedFunction function =
  modify' (\state -> state {generatedFunctions = generatedFunctions state <> [function]})

freeVarsRhs :: STGRhs -> Set.Set RName
freeVarsRhs = \case
  STGFunction binders body ->
    freeVarsExpr body `Set.difference` Set.fromList (map stgBinderName binders)
  STGThunk _ body ->
    freeVarsExpr body
  STGConstructor _ fields _ ->
    Set.unions (map freeVarsAtom fields)

freeVarsExpr :: STGExpr -> Set.Set RName
freeVarsExpr = \case
  STGAtom atom ->
    freeVarsAtom atom
  STGApp callee arguments _ ->
    Set.insert callee (Set.unions (map freeVarsAtom arguments))
  STGLet bind body _ ->
    freeVarsBind bind <> (freeVarsExpr body `Set.difference` Set.fromList (map stgBinderName (stgBindersOf bind)))
  STGCase scrutinee binder alternatives _ ->
    freeVarsExpr scrutinee
      <> Set.unions
        [ freeVarsExpr body `Set.difference` Set.fromList (stgBinderName binder : map stgBinderName binders)
        | STGAlt _ binders body <- alternatives
        ]
  STGPrim _ arguments _ ->
    Set.unions (map freeVarsAtom arguments)

freeVarsBind :: STGBind -> Set.Set RName
freeVarsBind = \case
  STGNonRec _ rhs ->
    freeVarsRhs rhs
  STGRec pairs ->
    Set.unions (map (freeVarsRhs . snd) pairs)
      `Set.difference` Set.fromList [stgBinderName binder | (binder, _) <- pairs]

freeVarsAtom :: STGAtom -> Set.Set RName
freeVarsAtom = \case
  STGVar name _ -> Set.singleton name
  STGLit {} -> Set.empty
  STGCon {} -> Set.empty

bindPairs :: STGBind -> [(STGBinder, STGRhs)]
bindPairs = \case
  STGNonRec binder rhs -> [(binder, rhs)]
  STGRec pairs -> pairs

runtimeFunctions :: [LLVMFunction]
runtimeFunctions =
  [ processLifetimeAllocFunction
  , allocObjectFunction
  , makeIntFunction
  , makeBoolFunction
  , makeCharFunction
  , makeStringFunction
  , makeDataFunction
  , makeFunctionFunction
  , makeThunkFunction
  , forceFunction
  , expectIntFunction
  , expectBoolFunction
  , expectCharFunction
  , expectStringFunction
  , expectFunctionFunction
  , makeCharListFromCStringFunction
  , showIntFunction
  , putStrLnFunction
  , printCharListFunction
  ]

processLifetimeAllocFunction :: LLVMFunction
processLifetimeAllocFunction =
  LLVMFunction
    { functionName = processLifetimeAllocFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LI64, Register "size")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "mem")) LPtr (DirectCall "malloc") False [(LI64, OLocal LI64 (Register "size"))]
            , IIcmp (Register "is_null") ICmpEq LPtr (OLocal LPtr (Register "mem")) OConstNull
            ]
            (TCondBr (OLocal LI1 (Register "is_null")) "abort" "ok")
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        , LLVMBlock
            "ok"
            []
            (TRet LPtr (OLocal LPtr (Register "mem")))
        ]
    }

allocObjectFunction :: LLVMFunction
allocObjectFunction =
  LLVMFunction
    { functionName = allocObjectFunctionName
    , functionReturnType = LPtr
    , functionParams = []
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ICall (Just (Register "obj")) LPtr (DirectCall processLifetimeAllocFunctionName) False [(LI64, OConstInt LI64 objectSize)]]
            (TRet LPtr (OLocal LPtr (Register "obj")))
        ]
    }
makeIntFunction :: LLVMFunction
makeIntFunction =
  makeValueFunction
    makeIntFunctionName
    [(LI64, Register "value")]
    [ (0, LI64, OConstInt LI64 tagInt)
    , (1, LI64, OLocal LI64 (Register "value"))
    ]

makeBoolFunction :: LLVMFunction
makeBoolFunction =
  LLVMFunction
    { functionName = makeBoolFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LI1, Register "value")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "obj")) LPtr (DirectCall allocObjectFunctionName) False []
            , IGetElementPtr (Register "tag_ptr") objectType (OLocal LPtr (Register "obj")) objectField0
            , IStore LI64 (OConstInt LI64 tagBool) (OLocal LPtr (Register "tag_ptr"))
            , IZext (Register "payload") (OLocal LI1 (Register "value")) LI64
            , IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "obj")) objectField1
            , IStore LI64 (OLocal LI64 (Register "payload")) (OLocal LPtr (Register "payload_ptr"))
            ]
            (TRet LPtr (OLocal LPtr (Register "obj")))
        ]
    }

makeCharFunction :: LLVMFunction
makeCharFunction =
  makeValueFunction
    makeCharFunctionName
    [(LI64, Register "value")]
    [ (0, LI64, OConstInt LI64 tagChar)
    , (1, LI64, OLocal LI64 (Register "value"))
    ]

makeStringFunction :: LLVMFunction
makeStringFunction =
  makeValueFunction
    makeStringFunctionName
    [(LPtr, Register "value")]
    [ (0, LI64, OConstInt LI64 tagString)
    , (2, LPtr, OLocal LPtr (Register "value"))
    ]

makeDataFunction :: LLVMFunction
makeDataFunction =
  makeValueFunction
    makeDataFunctionName
    [(LI64, Register "constructor"), (LI64, Register "arity"), (LPtr, Register "fields")]
    [ (0, LI64, OConstInt LI64 tagData)
    , (1, LI64, OLocal LI64 (Register "constructor"))
    , (2, LPtr, OLocal LPtr (Register "fields"))
    , (5, LI64, OLocal LI64 (Register "arity"))
    ]

makeFunctionFunction :: LLVMFunction
makeFunctionFunction =
  makeValueFunction
    makeFunctionFunctionName
    [(LPtr, Register "code"), (LPtr, Register "env")]
    [ (0, LI64, OConstInt LI64 tagFunction)
    , (2, LPtr, OLocal LPtr (Register "code"))
    , (3, LPtr, OLocal LPtr (Register "env"))
    ]

makeThunkFunction :: LLVMFunction
makeThunkFunction =
  makeValueFunction
    makeThunkFunctionName
    [(LPtr, Register "code"), (LPtr, Register "env"), (LI64, Register "update")]
    [ (0, LI64, OConstInt LI64 tagThunk)
    , (2, LPtr, OLocal LPtr (Register "code"))
    , (3, LPtr, OLocal LPtr (Register "env"))
    , (4, LPtr, OConstNull)
    , (5, LI64, OLocal LI64 (Register "update"))
    ]

makeValueFunction :: Text -> [(LLVMType, Register)] -> [(Int, LLVMType, LLVMOperand)] -> LLVMFunction
makeValueFunction name params stores =
  LLVMFunction
    { functionName = name
    , functionReturnType = LPtr
    , functionParams = params
    , functionBlocks =
        [ LLVMBlock
            "entry"
            ( ICall (Just (Register "obj")) LPtr (DirectCall allocObjectFunctionName) False []
                : concatMap storeField stores
            )
            (TRet LPtr (OLocal LPtr (Register "obj")))
        ]
    }
 where
  storeField (index, ty, value) =
    [ IGetElementPtr (Register ("field" <> Text.pack (show index))) objectType (OLocal LPtr (Register "obj")) (objectField index)
    , IStore ty value (OLocal LPtr (Register ("field" <> Text.pack (show index))))
    ]

forceFunction :: LLVMFunction
forceFunction =
  LLVMFunction
    { functionName = forceFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LPtr, Register "obj")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [IIcmp (Register "is_null") ICmpEq LPtr (OLocal LPtr (Register "obj")) OConstNull]
            (TCondBr (OLocal LI1 (Register "is_null")) "abort" "check")
        , LLVMBlock
            "check"
            [ IGetElementPtr (Register "tag_ptr") objectType (OLocal LPtr (Register "obj")) objectField0
            , ILoad (Register "tag") LI64 (OLocal LPtr (Register "tag_ptr"))
            , IIcmp (Register "is_thunk") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagThunk)
            ]
            (TCondBr (OLocal LI1 (Register "is_thunk")) "enter_thunk" "not_thunk")
        , LLVMBlock
            "not_thunk"
            [IIcmp (Register "is_indirection") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagIndirection)]
            (TCondBr (OLocal LI1 (Register "is_indirection")) "indirection" "not_indirection")
        , LLVMBlock
            "indirection"
            [ IGetElementPtr (Register "value_ptr") objectType (OLocal LPtr (Register "obj")) objectField4
            , ILoad (Register "value") LPtr (OLocal LPtr (Register "value_ptr"))
            ]
            (TRet LPtr (OLocal LPtr (Register "value")))
        , LLVMBlock
            "not_indirection"
            [IIcmp (Register "is_blackhole") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagBlackHole)]
            (TCondBr (OLocal LI1 (Register "is_blackhole")) "abort" "return_value")
        , LLVMBlock
            "return_value"
            []
            (TRet LPtr (OLocal LPtr (Register "obj")))
        , LLVMBlock
            "enter_thunk"
            [ IStore LI64 (OConstInt LI64 tagBlackHole) (OLocal LPtr (Register "tag_ptr"))
            , IGetElementPtr (Register "code_ptr") objectType (OLocal LPtr (Register "obj")) objectField2
            , ILoad (Register "code") LPtr (OLocal LPtr (Register "code_ptr"))
            , IGetElementPtr (Register "env_ptr") objectType (OLocal LPtr (Register "obj")) objectField3
            , ILoad (Register "env") LPtr (OLocal LPtr (Register "env_ptr"))
            , IGetElementPtr (Register "update_ptr") objectType (OLocal LPtr (Register "obj")) objectField5
            , ILoad (Register "update") LI64 (OLocal LPtr (Register "update_ptr"))
            , ICall (Just (Register "result")) LPtr (IndirectCall (OLocal LPtr (Register "code"))) False [(LPtr, OLocal LPtr (Register "env"))]
            , IIcmp (Register "is_single") ICmpEq LI64 (OLocal LI64 (Register "update")) (OConstInt LI64 singleEntryCode)
            ]
            (TCondBr (OLocal LI1 (Register "is_single")) "single_entry" "update_thunk")
        , LLVMBlock
            "single_entry"
            [IStore LI64 (OConstInt LI64 tagThunk) (OLocal LPtr (Register "tag_ptr"))]
            (TRet LPtr (OLocal LPtr (Register "result")))
        , LLVMBlock
            "update_thunk"
            [ IGetElementPtr (Register "result_ptr") objectType (OLocal LPtr (Register "obj")) objectField4
            , IStore LPtr (OLocal LPtr (Register "result")) (OLocal LPtr (Register "result_ptr"))
            , IStore LI64 (OConstInt LI64 tagIndirection) (OLocal LPtr (Register "tag_ptr"))
            ]
            (TRet LPtr (OLocal LPtr (Register "result")))
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        ]
    }

expectIntFunction :: LLVMFunction
expectIntFunction =
  expectPayloadFunction expectIntFunctionName tagInt LI64 "int" (TRet LI64 (OLocal LI64 (Register "payload")))

expectBoolFunction :: LLVMFunction
expectBoolFunction =
  expectPayloadFunction
    expectBoolFunctionName
    tagBool
    LI1
    "bool"
    (TRet LI1 (OLocal LI1 (Register "is_true")))

expectCharFunction :: LLVMFunction
expectCharFunction =
  expectPayloadFunction
    expectCharFunctionName
    tagChar
    LI32
    "char"
    (TRet LI32 (OLocal LI32 (Register "char_i32")))

expectStringFunction :: LLVMFunction
expectStringFunction =
  expectPayloadFunction expectStringFunctionName tagString LPtr "string" (TRet LPtr (OLocal LPtr (Register "payload")))

expectFunctionFunction :: LLVMFunction
expectFunctionFunction =
  expectPayloadFunction expectFunctionName tagFunction LPtr "fun" (TRet LPtr (OLocal LPtr (Register "forced")))

showIntFunction :: LLVMFunction
showIntFunction =
  LLVMFunction
    { functionName = showIntFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LI64, Register "value")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "buffer")) LPtr (DirectCall processLifetimeAllocFunctionName) False [(LI64, OConstInt LI64 32)]
            , IGetElementPtr
                (Register "fmt")
                (LArray (Text.length intRawFormatBytes) LI8)
                (OGlobal LPtr "haskell2010_fmt_i64_raw")
                [(LI64, OConstInt LI64 0), (LI64, OConstInt LI64 0)]
            , ICall
                (Just (Register "written"))
                LI32
                (DirectCall "snprintf")
                True
                [ (LPtr, OLocal LPtr (Register "buffer"))
                , (LI64, OConstInt LI64 32)
                , (LPtr, OLocal LPtr (Register "fmt"))
                , (LI64, OLocal LI64 (Register "value"))
                ]
            , ICall
                (Just (Register "string"))
                LPtr
                (DirectCall makeCharListFromCStringFunctionName)
                False
                [(LPtr, OLocal LPtr (Register "buffer"))]
            ]
            (TRet LPtr (OLocal LPtr (Register "string")))
        ]
    }

makeCharListFromCStringFunction :: LLVMFunction
makeCharListFromCStringFunction =
  LLVMFunction
    { functionName = makeCharListFromCStringFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LPtr, Register "value")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ILoad (Register "byte") LI8 (OLocal LPtr (Register "value"))
            , IIcmp (Register "is_end") ICmpEq LI8 (OLocal LI8 (Register "byte")) (OConstInt LI8 0)
            ]
            (TCondBr (OLocal LI1 (Register "is_end")) "nil" "cons")
        , LLVMBlock
            "nil"
            [ ICall
                (Just (Register "nil_list"))
                LPtr
                (DirectCall makeDataFunctionName)
                False
                [ (LI64, OConstInt LI64 (constructorRuntimeTag listNilDataConName))
                , (LI64, OConstInt LI64 0)
                , (LPtr, OConstNull)
                ]
            ]
            (TRet LPtr (OLocal LPtr (Register "nil_list")))
        , LLVMBlock
            "cons"
            [ IZext (Register "char_i64") (OLocal LI8 (Register "byte")) LI64
            , ICall
                (Just (Register "head"))
                LPtr
                (DirectCall makeCharFunctionName)
                False
                [(LI64, OLocal LI64 (Register "char_i64"))]
            , IGetElementPtr
                (Register "next")
                LI8
                (OLocal LPtr (Register "value"))
                [(LI64, OConstInt LI64 1)]
            , ICall
                (Just (Register "tail"))
                LPtr
                (DirectCall makeCharListFromCStringFunctionName)
                False
                [(LPtr, OLocal LPtr (Register "next"))]
            , ICall
                (Just (Register "fields"))
                LPtr
                (DirectCall processLifetimeAllocFunctionName)
                False
                [(LI64, OConstInt LI64 16)]
            , IGetElementPtr (Register "head_slot") (LArray 2 LPtr) (OLocal LPtr (Register "fields")) [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 0)]
            , IStore LPtr (OLocal LPtr (Register "head")) (OLocal LPtr (Register "head_slot"))
            , IGetElementPtr (Register "tail_slot") (LArray 2 LPtr) (OLocal LPtr (Register "fields")) [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 1)]
            , IStore LPtr (OLocal LPtr (Register "tail")) (OLocal LPtr (Register "tail_slot"))
            , ICall
                (Just (Register "cons_list"))
                LPtr
                (DirectCall makeDataFunctionName)
                False
                [ (LI64, OConstInt LI64 (constructorRuntimeTag listConsDataConName))
                , (LI64, OConstInt LI64 2)
                , (LPtr, OLocal LPtr (Register "fields"))
                ]
            ]
            (TRet LPtr (OLocal LPtr (Register "cons_list")))
        ]
    }

putStrLnFunction :: LLVMFunction
putStrLnFunction =
  LLVMFunction
    { functionName = putStrLnFunctionName
    , functionReturnType = LVoid
    , functionParams = [(LPtr, Register "obj")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "forced")) LPtr (DirectCall forceFunctionName) False [(LPtr, OLocal LPtr (Register "obj"))]
            , IGetElementPtr (Register "tag_ptr") objectType (OLocal LPtr (Register "forced")) objectField0
            , ILoad (Register "tag") LI64 (OLocal LPtr (Register "tag_ptr"))
            , IIcmp (Register "is_string") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagString)
            ]
            (TCondBr (OLocal LI1 (Register "is_string")) "string" "data_check")
        , LLVMBlock
            "string"
            [ IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "forced")) objectField2
            , ILoad (Register "payload") LPtr (OLocal LPtr (Register "payload_ptr"))
            , IGetElementPtr
                (Register "fmt")
                (LArray (Text.length stringLineFormatBytes) LI8)
                (OGlobal LPtr "haskell2010_fmt_string_line")
                [(LI64, OConstInt LI64 0), (LI64, OConstInt LI64 0)]
            , ICall
                Nothing
                LI32
                (DirectCall "printf")
                True
                [(LPtr, OLocal LPtr (Register "fmt")), (LPtr, OLocal LPtr (Register "payload"))]
            ]
            TRetVoid
        , LLVMBlock
            "data_check"
            [IIcmp (Register "is_data") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagData)]
            (TCondBr (OLocal LI1 (Register "is_data")) "list" "abort")
        , LLVMBlock
            "list"
            [ ICall Nothing LVoid (DirectCall printCharListFunctionName) False [(LPtr, OLocal LPtr (Register "forced"))]
            , ICall Nothing LI32 (DirectCall "putchar") False [(LI32, OConstInt LI32 10)]
            ]
            TRetVoid
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        ]
    }

printCharListFunction :: LLVMFunction
printCharListFunction =
  LLVMFunction
    { functionName = printCharListFunctionName
    , functionReturnType = LVoid
    , functionParams = [(LPtr, Register "obj")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "forced")) LPtr (DirectCall forceFunctionName) False [(LPtr, OLocal LPtr (Register "obj"))]
            , IGetElementPtr (Register "tag_ptr") objectType (OLocal LPtr (Register "forced")) objectField0
            , ILoad (Register "tag") LI64 (OLocal LPtr (Register "tag_ptr"))
            , IIcmp (Register "is_data") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 tagData)
            ]
            (TCondBr (OLocal LI1 (Register "is_data")) "data" "abort")
        , LLVMBlock
            "data"
            [ IGetElementPtr (Register "constructor_ptr") objectType (OLocal LPtr (Register "forced")) objectField1
            , ILoad (Register "constructor") LI64 (OLocal LPtr (Register "constructor_ptr"))
            , IIcmp (Register "is_nil") ICmpEq LI64 (OLocal LI64 (Register "constructor")) (OConstInt LI64 (constructorRuntimeTag listNilDataConName))
            ]
            (TCondBr (OLocal LI1 (Register "is_nil")) "nil" "cons_check")
        , LLVMBlock
            "nil"
            []
            TRetVoid
        , LLVMBlock
            "cons_check"
            [IIcmp (Register "is_cons") ICmpEq LI64 (OLocal LI64 (Register "constructor")) (OConstInt LI64 (constructorRuntimeTag listConsDataConName))]
            (TCondBr (OLocal LI1 (Register "is_cons")) "cons" "abort")
        , LLVMBlock
            "cons"
            [ IGetElementPtr (Register "fields_ptr") objectType (OLocal LPtr (Register "forced")) objectField2
            , ILoad (Register "fields") LPtr (OLocal LPtr (Register "fields_ptr"))
            , IGetElementPtr (Register "head_slot") (LArray 2 LPtr) (OLocal LPtr (Register "fields")) [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 0)]
            , ILoad (Register "head") LPtr (OLocal LPtr (Register "head_slot"))
            , IGetElementPtr (Register "tail_slot") (LArray 2 LPtr) (OLocal LPtr (Register "fields")) [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 1)]
            , ILoad (Register "tail") LPtr (OLocal LPtr (Register "tail_slot"))
            , ICall (Just (Register "head_forced")) LPtr (DirectCall forceFunctionName) False [(LPtr, OLocal LPtr (Register "head"))]
            , IGetElementPtr (Register "head_tag_ptr") objectType (OLocal LPtr (Register "head_forced")) objectField0
            , ILoad (Register "head_tag") LI64 (OLocal LPtr (Register "head_tag_ptr"))
            , IIcmp (Register "is_char") ICmpEq LI64 (OLocal LI64 (Register "head_tag")) (OConstInt LI64 tagChar)
            ]
            (TCondBr (OLocal LI1 (Register "is_char")) "char" "abort")
        , LLVMBlock
            "char"
            [ IGetElementPtr (Register "char_ptr") objectType (OLocal LPtr (Register "head_forced")) objectField1
            , ILoad (Register "char_i64") LI64 (OLocal LPtr (Register "char_ptr"))
            , ITrunc (Register "char_i32") (OLocal LI64 (Register "char_i64")) LI32
            , ICall Nothing LI32 (DirectCall "putchar") False [(LI32, OLocal LI32 (Register "char_i32"))]
            , ICall Nothing LVoid (DirectCall printCharListFunctionName) False [(LPtr, OLocal LPtr (Register "tail"))]
            ]
            TRetVoid
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        ]
    }

expectPayloadFunction :: Text -> Integer -> LLVMType -> Text -> LLVMTerminator -> LLVMFunction
expectPayloadFunction name expectedTag _ prefix successTerminator =
  LLVMFunction
    { functionName = name
    , functionReturnType = returnType
    , functionParams = [(LPtr, Register "obj")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "forced")) LPtr (DirectCall forceFunctionName) False [(LPtr, OLocal LPtr (Register "obj"))]
            , IGetElementPtr (Register "tag_ptr") objectType (OLocal LPtr (Register "forced")) objectField0
            , ILoad (Register "tag") LI64 (OLocal LPtr (Register "tag_ptr"))
            , IIcmp (Register "tag_ok") ICmpEq LI64 (OLocal LI64 (Register "tag")) (OConstInt LI64 expectedTag)
            ]
            (TCondBr (OLocal LI1 (Register "tag_ok")) "ok" "abort")
        , LLVMBlock
            "ok"
            (payloadInstructions prefix)
            successTerminator
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        ]
    }
 where
  returnType =
    case successTerminator of
      TRet ty _ -> ty
      TRetVoid -> LVoid
      _ -> LPtr
  payloadInstructions "int" =
    [ IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "forced")) objectField1
    , ILoad (Register "payload") LI64 (OLocal LPtr (Register "payload_ptr"))
    ]
  payloadInstructions "bool" =
    [ IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "forced")) objectField1
    , ILoad (Register "payload") LI64 (OLocal LPtr (Register "payload_ptr"))
    , IIcmp (Register "is_true") ICmpEq LI64 (OLocal LI64 (Register "payload")) (OConstInt LI64 1)
    ]
  payloadInstructions "char" =
    [ IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "forced")) objectField1
    , ILoad (Register "payload") LI64 (OLocal LPtr (Register "payload_ptr"))
    , ITrunc (Register "char_i32") (OLocal LI64 (Register "payload")) LI32
    ]
  payloadInstructions "string" =
    [ IGetElementPtr (Register "payload_ptr") objectType (OLocal LPtr (Register "forced")) objectField2
    , ILoad (Register "payload") LPtr (OLocal LPtr (Register "payload_ptr"))
    ]
  payloadInstructions _ =
    []

objectType :: LLVMType
objectType =
  LStruct [LI64, LI64, LPtr, LPtr, LPtr, LI64]

objectSize :: Integer
objectSize =
  48

objectField :: Int -> [(LLVMType, LLVMOperand)]
objectField index =
  [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 (fromIntegral index))]

objectField0, objectField1, objectField2, objectField3, objectField4, objectField5 :: [(LLVMType, LLVMOperand)]
objectField0 = objectField 0
objectField1 = objectField 1
objectField2 = objectField 2
objectField3 = objectField 3
objectField4 = objectField 4
objectField5 = objectField 5

tagInt, tagBool, tagFunction, tagThunk, tagBlackHole, tagIndirection, tagData, tagChar, tagString :: Integer
tagInt = 0
tagBool = 1
tagFunction = 2
tagThunk = 3
tagBlackHole = 4
tagIndirection = 5
tagData = 6
tagChar = 7
tagString = 8

updatableCode, singleEntryCode :: Integer
updatableCode = 0
singleEntryCode = 1

updateFlagCode :: STGUpdateFlag -> Integer
updateFlagCode = \case
  Updatable -> updatableCode
  SingleEntry -> singleEntryCode

constructorRuntimeTag :: RName -> Integer
constructorRuntimeTag =
  fromIntegral . nameUnique

processLifetimeAllocFunctionName, allocObjectFunctionName, makeIntFunctionName, makeBoolFunctionName, makeCharFunctionName, makeStringFunctionName, makeDataFunctionName :: Text
processLifetimeAllocFunctionName = "hegglog_hs_alloc_process_lifetime"
allocObjectFunctionName = "hegglog_hs_alloc_object"
makeIntFunctionName = "hegglog_hs_make_int"
makeBoolFunctionName = "hegglog_hs_make_bool"
makeCharFunctionName = "hegglog_hs_make_char"
makeStringFunctionName = "hegglog_hs_make_string"
makeDataFunctionName = "hegglog_hs_make_data"

makeFunctionFunctionName, makeThunkFunctionName, forceFunctionName :: Text
makeFunctionFunctionName = "hegglog_hs_make_function"
makeThunkFunctionName = "hegglog_hs_make_thunk"
forceFunctionName = "hegglog_hs_force"

expectIntFunctionName, expectBoolFunctionName, expectCharFunctionName, expectStringFunctionName, expectFunctionName, makeCharListFromCStringFunctionName, showIntFunctionName, putStrLnFunctionName, printCharListFunctionName :: Text
expectIntFunctionName = "hegglog_hs_expect_int"
expectBoolFunctionName = "hegglog_hs_expect_bool"
expectCharFunctionName = "hegglog_hs_expect_char"
expectStringFunctionName = "hegglog_hs_expect_string"
expectFunctionName = "hegglog_hs_expect_function"
makeCharListFromCStringFunctionName = "hegglog_hs_make_char_list_from_cstring"
showIntFunctionName = "hegglog_hs_show_int"
putStrLnFunctionName = "hegglog_hs_putstrln"
printCharListFunctionName = "hegglog_hs_print_char_list"

formatGlobals :: [LLVMGlobal]
formatGlobals =
  [ LLVMStringGlobal "haskell2010_fmt_i64" intFormatBytes
  , LLVMStringGlobal "haskell2010_fmt_i1" boolFormatBytes
  , LLVMStringGlobal "haskell2010_fmt_char" charFormatBytes
  , LLVMStringGlobal "haskell2010_fmt_i64_raw" intRawFormatBytes
  , LLVMStringGlobal "haskell2010_fmt_string_line" stringLineFormatBytes
  ]

runtimeDeclarations :: [Text]
runtimeDeclarations =
  [ "declare i32 @printf(ptr, ...)"
  , "declare i32 @putchar(i32)"
  , "declare i32 @snprintf(ptr, i64, ptr, ...)"
  , "declare noalias ptr @malloc(i64)"
  , "declare void @abort()"
  , "declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)"
  , "declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)"
  , "declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)"
  ]

intFormatBytes :: Text
intFormatBytes =
  "%lld\n\0"

boolFormatBytes :: Text
boolFormatBytes =
  "%d\n\0"

charFormatBytes :: Text
charFormatBytes =
  "%c\n\0"

intRawFormatBytes :: Text
intRawFormatBytes =
  "%lld\0"

stringLineFormatBytes :: Text
stringLineFormatBytes =
  "%s\n\0"

minInt64Value :: Integer
minInt64Value =
  -9223372036854775808

sanitizeName :: Text -> Text
sanitizeName =
  Text.concatMap encode
 where
  encode c
    | c >= 'a' && c <= 'z' = Text.singleton c
    | c >= 'A' && c <= 'Z' = Text.singleton c
    | c >= '0' && c <= '9' = Text.singleton c
    | c == '_' = "_u"
    | otherwise = "_x" <> Text.pack (showHex (ord c) "") <> "_"

throwSTGLLVM :: STGLLVMError -> FunctionM a
throwSTGLLVM =
  lift . lift . Left

mapLeft :: (a -> b) -> Either a c -> Either b c
mapLeft f = \case
  Left value -> Left (f value)
  Right value -> Right value

renderSTGLLVMError :: STGLLVMError -> Text
renderSTGLLVMError = \case
  STGLLVMInvalidSTG errors ->
    "invalid STG before native lowering: "
      <> Text.intercalate "; " (map STGValidate.renderSTGValidationError errors)
  STGLLVMUnknownMain occurrence ->
    "native Haskell 2010 output requires a `"
      <> occurrence
      <> "` binding"
  STGLLVMAmbiguousMain occurrence names ->
    "native Haskell 2010 output found multiple `"
      <> occurrence
      <> "` bindings: "
      <> Text.intercalate ", " (map renderRName names)
  STGLLVMUnsupported message ->
    "unsupported native Haskell 2010 STG form: " <> message
  STGLLVMInvalidLLVM err ->
    "invalid LLVM generated from Haskell 2010 STG: " <> renderLLVMValidationError err
