; generated by Haskell Compiler LLVM backend v0
; Int is lowered to checked signed i64; Bool is lowered to i1
; lowered from ANF
; source type: Bool
; egglog: disabled

@fmt_i64 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@fmt_i1 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)
define i1 @haskell_compiler_main_i1() {
entry:
  %v0 = icmp slt i64 1, 2
  ret i1 %v0
}

define i32 @main() {
entry:
  %result0 = call i1 @haskell_compiler_main_i1()
  %bool1 = zext i1 %result0 to i32
  %fmt2 = getelementptr inbounds [4 x i8], ptr @fmt_i1, i64 0, i64 0
  %printed3 = call i32 (ptr, ...) @printf(ptr %fmt2, i32 %bool1)
  ret i32 0
}
