; generated by HeggLog LLVM backend v0
; Int is lowered to signed i64; Bool is lowered to i1
; lowered from ANF
; source type: Int
; egglog: disabled

@fmt_i64 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@fmt_i1 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)
define i64 @hegglog_main_i64() {
entry:
  %v0 = add i64 3, 4
  %v1 = mul i64 %v0, 2
  ret i64 %v1
}

define i32 @main() {
entry:
  %result0 = call i64 @hegglog_main_i64()
  %fmt1 = getelementptr inbounds [6 x i8], ptr @fmt_i64, i64 0, i64 0
  %printed2 = call i32 (ptr, ...) @printf(ptr %fmt1, i64 %result0)
  ret i32 0
}
