; generated by HeggLog LLVM backend v0
; Int is lowered to signed i64; Bool is lowered to i1
; lowered from ANF
; source type: Int
; egglog: disabled

@fmt_i64 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@fmt_i1 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)
define i64 @hegglog_main_i64() {
entry:
  %v0 = icmp slt i64 3, 5
  br i1 %v0, label %then0, label %else1
then0:
  %v1 = mul i64 3, 2
  br label %join2
else1:
  %v2 = mul i64 3, 3
  br label %join2
join2:
  %phi3 = phi i64 [ %v1, %then0 ], [ %v2, %else1 ]
  ret i64 %phi3
}

define i32 @main() {
entry:
  %result0 = call i64 @hegglog_main_i64()
  %fmt1 = getelementptr inbounds [6 x i8], ptr @fmt_i64, i64 0, i64 0
  %printed2 = call i32 (ptr, ...) @printf(ptr %fmt1, i64 %result0)
  ret i32 0
}
