; generated by Haskell Compiler LLVM backend v0
; Int is lowered to checked signed i64; Bool is lowered to i1
; lowered from ANF
; source type: Int
; egglog: disabled

@fmt_i64 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@fmt_i1 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare void @abort()
define i64 @haskell_compiler_main_i64() {
entry:
  %checked0 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 3, i64 4)
  %v1 = extractvalue { i64, i1 } %checked0, 0
  %overflow2 = extractvalue { i64, i1 } %checked0, 1
  br i1 %overflow2, label %int_overflow0, label %int_ok1
int_overflow0:
  call void @abort()
  unreachable
int_ok1:
  %checked3 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %v1, i64 2)
  %v4 = extractvalue { i64, i1 } %checked3, 0
  %overflow5 = extractvalue { i64, i1 } %checked3, 1
  br i1 %overflow5, label %int_overflow2, label %int_ok3
int_overflow2:
  call void @abort()
  unreachable
int_ok3:
  ret i64 %v4
}

define i32 @main() {
entry:
  %result0 = call i64 @haskell_compiler_main_i64()
  %fmt1 = getelementptr inbounds [6 x i8], ptr @fmt_i64, i64 0, i64 0
  %printed2 = call i32 (ptr, ...) @printf(ptr %fmt1, i64 %result0)
  ret i32 0
}
