; generated by Haskell Compiler LLVM backend v0
; Int is lowered to checked signed i64; Bool is lowered to i1
; lowered from ANF
; source type: Int
; egglog: disabled

@fmt_i64 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@fmt_i1 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare void @abort()
define i64 @haskell_compiler_main_i64() {
entry:
  %v0 = icmp slt i64 3, 5
  br i1 %v0, label %then0, label %else1
then0:
  %checked1 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 3, i64 2)
  %v2 = extractvalue { i64, i1 } %checked1, 0
  %overflow3 = extractvalue { i64, i1 } %checked1, 1
  br i1 %overflow3, label %int_overflow3, label %int_ok4
int_overflow3:
  call void @abort()
  unreachable
int_ok4:
  br label %join2
else1:
  %checked4 = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 3, i64 3)
  %v5 = extractvalue { i64, i1 } %checked4, 0
  %overflow6 = extractvalue { i64, i1 } %checked4, 1
  br i1 %overflow6, label %int_overflow5, label %int_ok6
int_overflow5:
  call void @abort()
  unreachable
int_ok6:
  br label %join2
join2:
  %phi7 = phi i64 [ %v2, %int_ok4 ], [ %v5, %int_ok6 ]
  ret i64 %phi7
}

define i32 @main() {
entry:
  %result0 = call i64 @haskell_compiler_main_i64()
  %fmt1 = getelementptr inbounds [6 x i8], ptr @fmt_i64, i64 0, i64 0
  %printed2 = call i32 (ptr, ...) @printf(ptr %fmt1, i64 %result0)
  ret i32 0
}
