module Backend.LLVM.Lower
  ( LLVMLowerError (..)
  , lowerBackendToLLVM
  , renderLLVMLowerError
  )
where

import Control.Monad.State.Strict (State, evalState, get, modify')
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import qualified Data.Text as Text
import Backend.IR
import Backend.LLVM.IR
import Backend.LLVM.Validate
import Backend.Validate
import Syntax.AST (Name)
import Syntax.Pretty (prettyName, renderDoc)

data LLVMLowerError
  = LLVMBackendValidationFailed BackendValidationError
  | LLVMValidationFailed LLVMValidationError
  | LLVMUnboundVariable Name
  deriving stock (Show, Eq)

type ValueEnv = Map.Map Name LLVMOperand

data FunctionState = FunctionState
  { nextRegister :: Int
  , nextBlock :: Int
  , completedBlocks :: [LLVMBlock]
  , currentLabel :: Text
  , currentInstructions :: [LLVMInstruction]
  }
  deriving stock (Show, Eq)

lowerBackendToLLVM :: BackendProgram -> Either LLVMLowerError LLVMModule
lowerBackendToLLVM program = do
  mapLeft LLVMBackendValidationFailed (validateBackendProgram program)
  let rootFunction = lowerRootFunction program
      mainFunction = lowerMainFunction (backendRootType program)
      llvmModule =
        LLVMModule
          { moduleComments =
              [ "generated by HeggLog LLVM backend v0"
              , "Int is lowered to signed i64; Bool is lowered to i1"
              ]
                <> backendProvenance program
          , moduleGlobals = formatGlobals
          , moduleDeclarations = ["declare i32 @printf(ptr, ...)"]
          , moduleFunctions = [rootFunction, mainFunction]
          }
  mapLeft LLVMValidationFailed (validateLLVMModule llvmModule)
  pure llvmModule

lowerRootFunction :: BackendProgram -> LLVMFunction
lowerRootFunction program =
  let state0 =
        FunctionState
          { nextRegister = 0
          , nextBlock = 0
          , completedBlocks = []
          , currentLabel = "entry"
          , currentInstructions = []
          }
      returnType = llvmType (backendRootType program)
      blocks =
        evalState
          ( do
              value <- emitExpr Map.empty (backendRoot program)
              terminate (TRet returnType value)
          )
          state0
   in LLVMFunction
        { functionName = rootFunctionName (backendRootType program)
        , functionReturnType = returnType
        , functionBlocks = blocks
        }

lowerMainFunction :: BackendType -> LLVMFunction
lowerMainFunction rootType =
  let state0 =
        FunctionState
          { nextRegister = 0
          , nextBlock = 0
          , completedBlocks = []
          , currentLabel = "entry"
          , currentInstructions = []
          }
      blocks =
        evalState
          ( do
              resultReg <- freshRegister "result"
              emit (ICall (Just resultReg) (llvmType rootType) (rootFunctionName rootType) False [])
              let result = OLocal (llvmType rootType) resultReg
              printedValue <- printableValue rootType result
              fmt <- formatPointer rootType
              printedReg <- freshRegister "printed"
              emit (ICall (Just printedReg) LI32 "printf" True [(LPtr, fmt), (operandType printedValue, printedValue)])
              terminate (TRet LI32 (OConstInt LI32 0))
          )
          state0
   in LLVMFunction
        { functionName = "main"
        , functionReturnType = LI32
        , functionBlocks = blocks
        }

emitExpr :: ValueEnv -> BackendExpr -> State FunctionState LLVMOperand
emitExpr env = \case
  BEAtom _ atom ->
    emitAtom env atom
  BEPrim _ prim lhs rhs -> do
    lhsOperand <- emitAtom env lhs
    rhsOperand <- emitAtom env rhs
    reg <- freshRegister "v"
    emit $
      case prim of
        BPAdd -> IAdd reg LI64 lhsOperand rhsOperand
        BPSub -> ISub reg LI64 lhsOperand rhsOperand
        BPMul -> IMul reg LI64 lhsOperand rhsOperand
        BPLt -> IIcmp reg ICmpSlt LI64 lhsOperand rhsOperand
        BPEq operandTy -> IIcmp reg ICmpEq (llvmType operandTy) lhsOperand rhsOperand
    pure (OLocal (backendPrimResultLLVMType prim) reg)
  BEIf ty cond thenBranch elseBranch -> do
    condOperand <- emitAtom env cond
    thenLabel <- freshBlockLabel "then"
    elseLabel <- freshBlockLabel "else"
    joinLabel <- freshBlockLabel "join"
    terminateCurrent (TCondBr condOperand thenLabel elseLabel)

    startBlock thenLabel
    thenValue <- emitExpr env thenBranch
    thenPred <- getsCurrentLabel
    terminateCurrent (TBr joinLabel)

    startBlock elseLabel
    elseValue <- emitExpr env elseBranch
    elsePred <- getsCurrentLabel
    terminateCurrent (TBr joinLabel)

    startBlock joinLabel
    reg <- freshRegister "phi"
    let resultType = llvmType ty
    emit (IPhi reg resultType [(thenValue, thenPred), (elseValue, elsePred)])
    pure (OLocal resultType reg)
  BELet _ name rhs body -> do
    rhsValue <- emitExpr env rhs
    emitExpr (Map.insert name rhsValue env) body

emitAtom :: ValueEnv -> BackendAtom -> State FunctionState LLVMOperand
emitAtom env = \case
  BVar name ->
    case Map.lookup name env of
      Just value -> pure value
      Nothing -> pure (OLocal LI64 (Register ("__unbound_" <> sanitizeName (renderDoc (prettyName name)))))
  BInt n ->
    pure (OConstInt LI64 n)
  BBool True ->
    pure (OConstInt LI1 1)
  BBool False ->
    pure (OConstInt LI1 0)

printableValue :: BackendType -> LLVMOperand -> State FunctionState LLVMOperand
printableValue = \case
  BI64 ->
    pure
  BI1 ->
    \value -> do
      reg <- freshRegister "bool"
      emit (IZext reg value LI32)
      pure (OLocal LI32 reg)

formatPointer :: BackendType -> State FunctionState LLVMOperand
formatPointer rootType = do
  reg <- freshRegister "fmt"
  let (globalName, byteCount) =
        case rootType of
          BI64 -> ("fmt_i64", Text.length intFormatBytes)
          BI1 -> ("fmt_i1", Text.length boolFormatBytes)
      arrayType = LArray byteCount LI8
      global = OGlobal LPtr globalName
  emit
    ( IGetElementPtr
        reg
        arrayType
        global
        [(LI64, OConstInt LI64 0), (LI64, OConstInt LI64 0)]
    )
  pure (OLocal LPtr reg)

terminate :: LLVMTerminator -> State FunctionState [LLVMBlock]
terminate terminator = do
  terminateCurrent terminator
  state <- get
  pure (completedBlocks state)

terminateCurrent :: LLVMTerminator -> State FunctionState ()
terminateCurrent terminator = do
  state <- get
  let block =
        LLVMBlock
          { blockLabel = currentLabel state
          , blockInstructions = currentInstructions state
          , blockTerminator = terminator
          }
  modify' $
    \st ->
      st
        { completedBlocks = completedBlocks st <> [block]
        , currentInstructions = []
        }

startBlock :: Text -> State FunctionState ()
startBlock label =
  modify' (\state -> state {currentLabel = label, currentInstructions = []})

emit :: LLVMInstruction -> State FunctionState ()
emit instruction =
  modify' (\state -> state {currentInstructions = currentInstructions state <> [instruction]})

freshRegister :: Text -> State FunctionState Register
freshRegister prefix = do
  state <- get
  let reg = Register (prefix <> Text.pack (show (nextRegister state)))
  modify' (\st -> st {nextRegister = nextRegister st + 1})
  pure reg

freshBlockLabel :: Text -> State FunctionState Text
freshBlockLabel prefix = do
  state <- get
  let label = prefix <> Text.pack (show (nextBlock state))
  modify' (\st -> st {nextBlock = nextBlock st + 1})
  pure label

getsCurrentLabel :: State FunctionState Text
getsCurrentLabel =
  currentLabel <$> get

backendPrimResultLLVMType :: BackendPrim -> LLVMType
backendPrimResultLLVMType =
  llvmType . backendPrimResultType

llvmType :: BackendType -> LLVMType
llvmType = \case
  BI64 -> LI64
  BI1 -> LI1

rootFunctionName :: BackendType -> Text
rootFunctionName = \case
  BI64 -> "hegglog_main_i64"
  BI1 -> "hegglog_main_i1"

formatGlobals :: [LLVMGlobal]
formatGlobals =
  [ LLVMStringGlobal "fmt_i64" intFormatBytes
  , LLVMStringGlobal "fmt_i1" boolFormatBytes
  ]

intFormatBytes :: Text
intFormatBytes =
  "%lld\n\0"

boolFormatBytes :: Text
boolFormatBytes =
  "%d\n\0"

renderLLVMLowerError :: LLVMLowerError -> Text
renderLLVMLowerError = \case
  LLVMBackendValidationFailed err ->
    renderBackendValidationError err
  LLVMValidationFailed err ->
    renderLLVMValidationError err
  LLVMUnboundVariable name ->
    "unbound LLVM lowering variable " <> renderDoc (prettyName name)

sanitizeName :: Text -> Text
sanitizeName =
  Text.map replace
 where
  replace c
    | c >= 'a' && c <= 'z' = c
    | c >= 'A' && c <= 'Z' = c
    | c >= '0' && c <= '9' = c
    | otherwise = '_'

mapLeft :: (a -> b) -> Either a c -> Either b c
mapLeft f = \case
  Left value -> Left (f value)
  Right value -> Right value
