module Backend.LLVM.Lower
  ( LLVMLowerError (..)
  , lowerBackendToLLVM
  , renderLLVMLowerError
  )
where

import Control.Monad.Except (ExceptT, runExceptT, throwError)
import Control.Monad.State.Strict (State, evalState, get, modify')
import Data.Char (ord)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as Text
import Numeric (showHex)
import Backend.IR
import Backend.LLVM.IR
import Backend.LLVM.Validate
import Backend.Validate
import Runtime.Int (hintToInteger)
import Syntax.AST (Name)
import Syntax.Pretty (prettyName, renderDoc)

data LLVMLowerError
  = LLVMBackendValidationFailed BackendValidationError
  | LLVMValidationFailed LLVMValidationError
  | LLVMUnboundVariable Name
  deriving stock (Show, Eq)

type ValueEnv = Map.Map Name LLVMOperand

type LowerM = ExceptT LLVMLowerError (State FunctionState)

data FunctionState = FunctionState
  { nextRegister :: Int
  , nextBlock :: Int
  , completedBlocks :: [LLVMBlock]
  , currentLabel :: Text
  , currentInstructions :: [LLVMInstruction]
  }
  deriving stock (Show, Eq)

lowerBackendToLLVM :: BackendProgram -> Either LLVMLowerError LLVMModule
lowerBackendToLLVM program = do
  mapLeft LLVMBackendValidationFailed (validateBackendProgram program)
  topFunctions <- traverse lowerBackendFunction (backendFunctions program)
  rootFunction <- lowerRootFunction program
  mainFunction <- lowerMainFunction (backendRootType program)
  let llvmModule =
        LLVMModule
          { moduleComments =
              [ "generated by Haskell Compiler LLVM backend v0"
              , "Int is lowered to checked signed i64; Bool is lowered to i1"
              ]
                <> allocationPolicyComments program
                <> backendProvenance program
          , moduleGlobals = formatGlobals
          , moduleDeclarations = runtimeDeclarations program
          , moduleFunctions = topFunctions <> runtimeFunctions program <> [rootFunction, mainFunction]
          }
  mapLeft LLVMValidationFailed (validateLLVMModule llvmModule)
  pure llvmModule

lowerRootFunction :: BackendProgram -> Either LLVMLowerError LLVMFunction
lowerRootFunction program =
  let state0 =
        FunctionState
          { nextRegister = 0
          , nextBlock = 0
          , completedBlocks = []
          , currentLabel = "entry"
          , currentInstructions = []
          }
      returnType = llvmType (backendRootType program)
   in do
        blocks <-
          runLowerM state0 $ do
            value <- emitExpr Map.empty (backendRoot program)
            terminate (TRet returnType value)
        pure
          LLVMFunction
            { functionName = rootFunctionName (backendRootType program)
            , functionReturnType = returnType
            , functionParams = []
            , functionBlocks = blocks
            }

lowerBackendFunction :: BackendFunction -> Either LLVMLowerError LLVMFunction
lowerBackendFunction function =
  let state0 =
        FunctionState
          { nextRegister = 0
          , nextBlock = 0
          , completedBlocks = []
          , currentLabel = "entry"
          , currentInstructions = []
          }
      params =
        [ (llvmType ty, paramRegister name)
        | (name, ty) <- backendFunctionParams function
        ]
      env =
        Map.fromList
          [ (name, OLocal (llvmType ty) (paramRegister name))
          | (name, ty) <- backendFunctionParams function
          ]
      returnType = llvmType (backendFunctionReturnType function)
   in do
        blocks <-
          runLowerM state0 $ do
            value <- emitExpr env (backendFunctionBody function)
            terminate (TRet returnType value)
        pure
          LLVMFunction
            { functionName = topFunctionName (backendFunctionName function)
            , functionReturnType = returnType
            , functionParams = params
            , functionBlocks = blocks
            }

lowerMainFunction :: BackendType -> Either LLVMLowerError LLVMFunction
lowerMainFunction rootType =
  let state0 =
        FunctionState
          { nextRegister = 0
          , nextBlock = 0
          , completedBlocks = []
          , currentLabel = "entry"
          , currentInstructions = []
          }
   in do
        blocks <-
          runLowerM state0 $ do
            resultReg <- freshRegister "result"
            emit (ICall (Just resultReg) (llvmType rootType) (DirectCall (rootFunctionName rootType)) False [])
            let result = OLocal (llvmType rootType) resultReg
            printedValue <- printableValue rootType result
            fmt <- formatPointer rootType
            printedReg <- freshRegister "printed"
            emit (ICall (Just printedReg) LI32 (DirectCall "printf") True [(LPtr, fmt), (operandType printedValue, printedValue)])
            terminate (TRet LI32 (OConstInt LI32 0))
        pure
          LLVMFunction
            { functionName = "main"
            , functionReturnType = LI32
            , functionParams = []
            , functionBlocks = blocks
            }

runLowerM :: FunctionState -> LowerM a -> Either LLVMLowerError a
runLowerM state0 action =
  evalState (runExceptT action) state0

emitExpr :: ValueEnv -> BackendExpr -> LowerM LLVMOperand
emitExpr env = \case
  BEAtom _ atom ->
    emitAtom env atom
  BEPrim _ prim lhs rhs -> do
    lhsOperand <- emitAtom env lhs
    rhsOperand <- emitAtom env rhs
    case prim of
      BPAdd -> emitCheckedIntPrim "llvm.sadd.with.overflow.i64" lhsOperand rhsOperand
      BPSub -> emitCheckedIntPrim "llvm.ssub.with.overflow.i64" lhsOperand rhsOperand
      BPMul -> emitCheckedIntPrim "llvm.smul.with.overflow.i64" lhsOperand rhsOperand
      BPDiv -> emitCheckedDiv lhsOperand rhsOperand
      BPLt -> do
        reg <- freshRegister "v"
        emit (IIcmp reg ICmpSlt LI64 lhsOperand rhsOperand)
        pure (OLocal (backendPrimResultLLVMType prim) reg)
      BPEq operandTy -> do
        reg <- freshRegister "v"
        emit (IIcmp reg ICmpEq (llvmType operandTy) lhsOperand rhsOperand)
        pure (OLocal (backendPrimResultLLVMType prim) reg)
  BEIf ty cond thenBranch elseBranch -> do
    condOperand <- emitAtom env cond
    thenLabel <- freshBlockLabel "then"
    elseLabel <- freshBlockLabel "else"
    joinLabel <- freshBlockLabel "join"
    terminateCurrent (TCondBr condOperand thenLabel elseLabel)

    startBlock thenLabel
    thenValue <- emitExpr env thenBranch
    thenPred <- getsCurrentLabel
    terminateCurrent (TBr joinLabel)

    startBlock elseLabel
    elseValue <- emitExpr env elseBranch
    elsePred <- getsCurrentLabel
    terminateCurrent (TBr joinLabel)

    startBlock joinLabel
    reg <- freshRegister "phi"
    let resultType = llvmType ty
    emit (IPhi reg resultType [(thenValue, thenPred), (elseValue, elsePred)])
    pure (OLocal resultType reg)
  BELet _ name rhs body -> do
    rhsValue <- emitExpr env rhs
    emitExpr (Map.insert name rhsValue env) body
  BECall ty callee args -> do
    argOperands <- traverse (emitAtom env) args
    reg <- freshRegister "call"
    let returnType = llvmType ty
    emit (ICall (Just reg) returnType (DirectCall (topFunctionName callee)) False [(operandType arg, arg) | arg <- argOperands])
    pure (OLocal returnType reg)
  BEMakeClosure ty code captures -> do
    loweredCaptures <- traverse emitCapture captures
    emitClosureAllocation ty code loweredCaptures
  BEApply ty fn arg -> do
    closureOperand <- emitAtom env fn
    argOperand <- emitAtom env arg
    codeField <- closureFieldPointer (LStruct [LPtr]) closureOperand 0
    codeReg <- freshRegister "closure_code"
    emit (ILoad codeReg LPtr codeField)
    resultReg <- freshRegister "closure_call"
    let returnType = llvmType ty
        codeOperand = OLocal LPtr codeReg
    emit
      ( ICall
          (Just resultReg)
          returnType
          (IndirectCall codeOperand)
          False
          [(LPtr, closureOperand), (operandType argOperand, argOperand)]
      )
    pure (OLocal returnType resultReg)
  BEEnvGet ty fields envAtom index -> do
    envOperand <- emitAtom env envAtom
    fieldPtr <- envFieldPointer fields envOperand index
    reg <- freshRegister "env"
    emit (ILoad reg (llvmType ty) fieldPtr)
    pure (OLocal (llvmType ty) reg)
 where
  emitCapture (ty, atom) = do
    operand <- emitAtom env atom
    pure (ty, operand)

emitAtom :: ValueEnv -> BackendAtom -> LowerM LLVMOperand
emitAtom env = \case
  BVar name ->
    case Map.lookup name env of
      Just value -> pure value
      Nothing -> throwError (LLVMUnboundVariable name)
  BInt n ->
    pure (OConstInt LI64 (hintToInteger n))
  BBool True ->
    pure (OConstInt LI1 1)
  BBool False ->
    pure (OConstInt LI1 0)

printableValue :: BackendType -> LLVMOperand -> LowerM LLVMOperand
printableValue = \case
  BI64 ->
    pure
  BI1 ->
    \value -> do
      reg <- freshRegister "bool"
      emit (IZext reg value LI32)
      pure (OLocal LI32 reg)
  BClosure {} ->
    \_ -> throwError (LLVMValidationFailed (LLVMReturnTypeMismatch "main" LI64 LPtr))
  BEnv {} ->
    \_ -> throwError (LLVMValidationFailed (LLVMReturnTypeMismatch "main" LI64 LPtr))

formatPointer :: BackendType -> LowerM LLVMOperand
formatPointer rootType = do
  reg <- freshRegister "fmt"
  let (globalName, byteCount) =
        case rootType of
          BI64 -> ("fmt_i64", Text.length intFormatBytes)
          BI1 -> ("fmt_i1", Text.length boolFormatBytes)
          BClosure {} -> ("fmt_i64", Text.length intFormatBytes)
          BEnv {} -> ("fmt_i64", Text.length intFormatBytes)
      arrayType = LArray byteCount LI8
      global = OGlobal LPtr globalName
  emit
    ( IGetElementPtr
        reg
        arrayType
        global
        [(LI64, OConstInt LI64 0), (LI64, OConstInt LI64 0)]
    )
  pure (OLocal LPtr reg)

emitCheckedIntPrim :: Text -> LLVMOperand -> LLVMOperand -> LowerM LLVMOperand
emitCheckedIntPrim intrinsic lhs rhs = do
  pairReg <- freshRegister "checked"
  let pairType = LStruct [LI64, LI1]
  emit (ICall (Just pairReg) pairType (DirectCall intrinsic) False [(LI64, lhs), (LI64, rhs)])
  let pairOperand = OLocal pairType pairReg
  valueReg <- freshRegister "v"
  overflowReg <- freshRegister "overflow"
  emit (IExtractValue valueReg LI64 pairOperand 0)
  emit (IExtractValue overflowReg LI1 pairOperand 1)
  overflowLabel <- freshBlockLabel "int_overflow"
  continueLabel <- freshBlockLabel "int_ok"
  terminateCurrent (TCondBr (OLocal LI1 overflowReg) overflowLabel continueLabel)

  startBlock overflowLabel
  emit (ICall Nothing LVoid (DirectCall "abort") False [])
  terminateCurrent TUnreachable

  startBlock continueLabel
  pure (OLocal LI64 valueReg)

emitCheckedDiv :: LLVMOperand -> LLVMOperand -> LowerM LLVMOperand
emitCheckedDiv lhs rhs = do
  zeroReg <- freshRegister "div_zero"
  emit (IIcmp zeroReg ICmpEq LI64 rhs (OConstInt LI64 0))
  zeroLabel <- freshBlockLabel "div_zero_abort"
  nonZeroLabel <- freshBlockLabel "div_nonzero"
  terminateCurrent (TCondBr (OLocal LI1 zeroReg) zeroLabel nonZeroLabel)

  startBlock zeroLabel
  emit (ICall Nothing LVoid (DirectCall "abort") False [])
  terminateCurrent TUnreachable

  startBlock nonZeroLabel
  minReg <- freshRegister "div_min_lhs"
  emit (IIcmp minReg ICmpEq LI64 lhs (OConstInt LI64 minInt64Value))
  overflowCheckLabel <- freshBlockLabel "div_overflow_check"
  okLabel <- freshBlockLabel "div_ok"
  terminateCurrent (TCondBr (OLocal LI1 minReg) overflowCheckLabel okLabel)

  startBlock overflowCheckLabel
  negOneReg <- freshRegister "div_neg_one"
  emit (IIcmp negOneReg ICmpEq LI64 rhs (OConstInt LI64 (-1)))
  overflowLabel <- freshBlockLabel "div_overflow_abort"
  terminateCurrent (TCondBr (OLocal LI1 negOneReg) overflowLabel okLabel)

  startBlock overflowLabel
  emit (ICall Nothing LVoid (DirectCall "abort") False [])
  terminateCurrent TUnreachable

  startBlock okLabel
  valueReg <- freshRegister "v"
  emit (IDiv valueReg LI64 lhs rhs)
  pure (OLocal LI64 valueReg)

emitClosureAllocation :: BackendType -> Name -> [(BackendType, LLVMOperand)] -> LowerM LLVMOperand
emitClosureAllocation closureType code captures =
  case closureType of
    BClosure {} -> do
      allocReg <- freshRegister "closure"
      let closureStructType = LStruct (LPtr : map (llvmType . fst) captures)
          closureSize = 8 * fromIntegral (1 + length captures)
      emit (ICall (Just allocReg) LPtr (DirectCall processLifetimeAllocFunctionName) False [(LI64, OConstInt LI64 closureSize)])
      let closureOperand = OLocal LPtr allocReg
      codeField <- closureFieldPointer closureStructType closureOperand 0
      emit (IStore LPtr (OGlobal LPtr (topFunctionName code)) codeField)
      mapM_ (storeCapture closureStructType closureOperand) (zip [1 :: Int ..] captures)
      pure closureOperand
    other ->
      throwError (LLVMValidationFailed (LLVMOperandTypeMismatch LPtr (llvmType other) OConstNull))
 where
  storeCapture closureStructType closureOperand (index, (captureType, captureOperand)) = do
    fieldPtr <- closureFieldPointer closureStructType closureOperand index
    emit (IStore (llvmType captureType) captureOperand fieldPtr)

closureFieldPointer :: LLVMType -> LLVMOperand -> Int -> LowerM LLVMOperand
closureFieldPointer closureStructType closureOperand index = do
  fieldReg <- freshRegister "field"
  emit
    ( IGetElementPtr
        fieldReg
        closureStructType
        closureOperand
        [(LI32, OConstInt LI32 0), (LI32, OConstInt LI32 (fromIntegral index))]
    )
  pure (OLocal LPtr fieldReg)

envFieldPointer :: [BackendType] -> LLVMOperand -> Int -> LowerM LLVMOperand
envFieldPointer fields envOperand index = do
  let fieldIndex = index + 1
      envStructType = LStruct (LPtr : map llvmType fields)
  closureFieldPointer envStructType envOperand fieldIndex

terminate :: LLVMTerminator -> LowerM [LLVMBlock]
terminate terminator = do
  terminateCurrent terminator
  state <- get
  pure (completedBlocks state)

terminateCurrent :: LLVMTerminator -> LowerM ()
terminateCurrent terminator = do
  state <- get
  let block =
        LLVMBlock
          { blockLabel = currentLabel state
          , blockInstructions = currentInstructions state
          , blockTerminator = terminator
          }
  modify' $
    \st ->
      st
        { completedBlocks = completedBlocks st <> [block]
        , currentInstructions = []
        }

startBlock :: Text -> LowerM ()
startBlock label =
  modify' (\state -> state {currentLabel = label, currentInstructions = []})

emit :: LLVMInstruction -> LowerM ()
emit instruction =
  modify' (\state -> state {currentInstructions = currentInstructions state <> [instruction]})

freshRegister :: Text -> LowerM Register
freshRegister prefix = do
  state <- get
  let reg = Register (prefix <> Text.pack (show (nextRegister state)))
  modify' (\st -> st {nextRegister = nextRegister st + 1})
  pure reg

freshBlockLabel :: Text -> LowerM Text
freshBlockLabel prefix = do
  state <- get
  let label = prefix <> Text.pack (show (nextBlock state))
  modify' (\st -> st {nextBlock = nextBlock st + 1})
  pure label

getsCurrentLabel :: LowerM Text
getsCurrentLabel =
  currentLabel <$> get

backendPrimResultLLVMType :: BackendPrim -> LLVMType
backendPrimResultLLVMType =
  llvmType . backendPrimResultType

llvmType :: BackendType -> LLVMType
llvmType = \case
  BI64 -> LI64
  BI1 -> LI1
  BClosure {} -> LPtr
  BEnv {} -> LPtr

rootFunctionName :: BackendType -> Text
rootFunctionName = \case
  BI64 -> "haskell_compiler_main_i64"
  BI1 -> "haskell_compiler_main_i1"
  BClosure {} -> "haskell_compiler_main_closure"
  BEnv {} -> "haskell_compiler_main_env"

runtimeFunctions :: BackendProgram -> [LLVMFunction]
runtimeFunctions program
  | programAllocatesClosures program = [processLifetimeAllocFunction]
  | otherwise = []

allocationPolicyComments :: BackendProgram -> [Text]
allocationPolicyComments program
  | programAllocatesClosures program = ["heap allocations use a process-lifetime runtime allocator"]
  | otherwise = []

processLifetimeAllocFunction :: LLVMFunction
processLifetimeAllocFunction =
  LLVMFunction
    { functionName = processLifetimeAllocFunctionName
    , functionReturnType = LPtr
    , functionParams = [(LI64, Register "size")]
    , functionBlocks =
        [ LLVMBlock
            "entry"
            [ ICall (Just (Register "mem")) LPtr (DirectCall "malloc") False [(LI64, OLocal LI64 (Register "size"))]
            , IIcmp (Register "is_null") ICmpEq LPtr (OLocal LPtr (Register "mem")) OConstNull
            ]
            (TCondBr (OLocal LI1 (Register "is_null")) "abort" "ok")
        , LLVMBlock
            "abort"
            [ICall Nothing LVoid (DirectCall "abort") False []]
            TUnreachable
        , LLVMBlock
            "ok"
            []
            (TRet LPtr (OLocal LPtr (Register "mem")))
        ]
    }

formatGlobals :: [LLVMGlobal]
formatGlobals =
  [ LLVMStringGlobal "fmt_i64" intFormatBytes
  , LLVMStringGlobal "fmt_i1" boolFormatBytes
  ]

runtimeDeclarations :: BackendProgram -> [Text]
runtimeDeclarations program =
  "declare i32 @printf(ptr, ...)" : runtimeSupportDeclarations program

runtimeSupportDeclarations :: BackendProgram -> [Text]
runtimeSupportDeclarations program =
  let prims =
        checkedArithmeticPrims (backendRoot program)
          <> foldMap (checkedArithmeticPrims . backendFunctionBody) (backendFunctions program)
      hasClosures =
        programAllocatesClosures program
      intrinsic prim =
        case prim of
          BPAdd -> ["declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)"]
          BPSub -> ["declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)"]
          BPMul -> ["declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)"]
          BPDiv -> []
          _ -> []
      intrinsicDecls = concatMap intrinsic (Set.toList prims)
      mallocDecls =
        if hasClosures then ["declare noalias ptr @malloc(i64)"] else []
      abortDecls =
        if Set.null prims && not hasClosures then [] else ["declare void @abort()"]
   in intrinsicDecls <> mallocDecls <> abortDecls

programAllocatesClosures :: BackendProgram -> Bool
programAllocatesClosures program =
  containsClosureAllocation (backendRoot program)
    || any (containsClosureAllocation . backendFunctionBody) (backendFunctions program)

checkedArithmeticPrims :: BackendExpr -> Set.Set BackendPrim
checkedArithmeticPrims = \case
  BEAtom {} ->
    Set.empty
  BEPrim _ prim _ _ ->
    case prim of
      BPAdd -> Set.singleton prim
      BPSub -> Set.singleton prim
      BPMul -> Set.singleton prim
      BPDiv -> Set.singleton prim
      _ -> Set.empty
  BEIf _ _ thenBranch elseBranch ->
    checkedArithmeticPrims thenBranch <> checkedArithmeticPrims elseBranch
  BECall {} ->
    Set.empty
  BEMakeClosure {} ->
    Set.empty
  BEApply {} ->
    Set.empty
  BEEnvGet {} ->
    Set.empty
  BELet _ _ rhs body ->
    checkedArithmeticPrims rhs <> checkedArithmeticPrims body

containsClosureAllocation :: BackendExpr -> Bool
containsClosureAllocation = \case
  BEAtom {} ->
    False
  BEPrim {} ->
    False
  BEIf _ _ thenBranch elseBranch ->
    containsClosureAllocation thenBranch || containsClosureAllocation elseBranch
  BECall {} ->
    False
  BEMakeClosure {} ->
    True
  BEApply {} ->
    False
  BEEnvGet {} ->
    False
  BELet _ _ rhs body ->
    containsClosureAllocation rhs || containsClosureAllocation body

intFormatBytes :: Text
intFormatBytes =
  "%lld\n\0"

boolFormatBytes :: Text
boolFormatBytes =
  "%d\n\0"

minInt64Value :: Integer
minInt64Value =
  -9223372036854775808

processLifetimeAllocFunctionName :: Text
processLifetimeAllocFunctionName =
  "haskell_compiler_alloc_process_lifetime"

renderLLVMLowerError :: LLVMLowerError -> Text
renderLLVMLowerError = \case
  LLVMBackendValidationFailed err ->
    renderBackendValidationError err
  LLVMValidationFailed err ->
    renderLLVMValidationError err
  LLVMUnboundVariable name ->
    "unbound LLVM lowering variable " <> renderDoc (prettyName name)

sanitizeName :: Text -> Text
sanitizeName =
  Text.concatMap encode
 where
  encode c
    | c >= 'a' && c <= 'z' = Text.singleton c
    | c >= 'A' && c <= 'Z' = Text.singleton c
    | c >= '0' && c <= '9' = Text.singleton c
    | c == '_' = "_u"
    | otherwise = "_x" <> Text.pack (showHex (ord c) "") <> "_"

topFunctionName :: Name -> Text
topFunctionName name =
  "haskell_compiler_fun_" <> sanitizeName (renderDoc (prettyName name))

paramRegister :: Name -> Register
paramRegister name =
  Register ("arg_" <> sanitizeName (renderDoc (prettyName name)))

mapLeft :: (a -> b) -> Either a c -> Either b c
mapLeft f = \case
  Left value -> Left (f value)
  Right value -> Right value
